package view.gui;

import controller.*;
import exceptions.*;
import model.*;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.net.URISyntaxException;

/**
 * @author KNOWLES
 */
public class FMR_FaQ extends javax.swing.JFrame {
    private final Account account;
    private final FaQController faqController;
    
    /**
     * Creates new form FMR_FaQ
     */
    public FMR_FaQ(Account account) {
        FaQController tempController;
        try {
            tempController = new FaQController(new FileHandler<>(new FaQ()));
        } catch (FaQException e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.faqController = tempController;
        this.account = account;
        Toolkit t=Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("/resources/logo.png")));
        setTitle("LEVELING_UP_LIFE");
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        subtitulo = new javax.swing.JLabel();
        boton_events = new javax.swing.JToggleButton();
        boton_product = new javax.swing.JToggleButton();
        boton_salas = new javax.swing.JToggleButton();
        boton_FaQ = new javax.swing.JToggleButton();
        boton_booking = new javax.swing.JToggleButton();
        boton_logout = new javax.swing.JToggleButton();
        campo_question = new javax.swing.JTextField();
        boton_allQuestion = new javax.swing.JToggleButton();
        boton_sendQuestion = new javax.swing.JToggleButton();
        boton_comoLlegar = new javax.swing.JToggleButton();
        boton_contacto = new javax.swing.JToggleButton();
        boton_concepto = new javax.swing.JButton();
        boton_contacto1 = new javax.swing.JToggleButton();
        TITULO = new javax.swing.JPanel();
        boton_myCuenta = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(875, 555));

        BG.setBackground(new java.awt.Color(252, 240, 198));
        BG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BG.setMinimumSize(new java.awt.Dimension(860, 520));
        BG.setPreferredSize(new java.awt.Dimension(860, 520));
        BG.setRequestFocusEnabled(false);
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtitulo.setBackground(new java.awt.Color(0, 0, 0));
        subtitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        subtitulo.setForeground(new java.awt.Color(255, 255, 255));
        subtitulo.setText("Ingrese su pregunta ");
        BG.add(subtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 350, 40));

        boton_events.setBackground(new java.awt.Color(51, 153, 0));
        boton_events.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_events.setForeground(new java.awt.Color(255, 255, 255));
        boton_events.setText("Eventos");
        boton_events.setToolTipText("");
        boton_events.setAutoscrolls(true);
        boton_events.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_events.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eventsActionPerformed(evt);
            }
        });
        BG.add(boton_events, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        boton_product.setBackground(new java.awt.Color(51, 153, 0));
        boton_product.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_product.setForeground(new java.awt.Color(255, 255, 255));
        boton_product.setText("Productos");
        boton_product.setToolTipText("");
        boton_product.setAutoscrolls(true);
        boton_product.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_productActionPerformed(evt);
            }
        });
        BG.add(boton_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 30));

        boton_salas.setBackground(new java.awt.Color(51, 153, 0));
        boton_salas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_salas.setForeground(new java.awt.Color(255, 255, 255));
        boton_salas.setText("Salas");
        boton_salas.setToolTipText("");
        boton_salas.setAutoscrolls(true);
        boton_salas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_salas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salasActionPerformed(evt);
            }
        });
        BG.add(boton_salas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 30));

        boton_FaQ.setBackground(new java.awt.Color(43, 101, 153));
        boton_FaQ.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_FaQ.setForeground(new java.awt.Color(255, 255, 255));
        boton_FaQ.setText("FaQ");
        boton_FaQ.setToolTipText("");
        boton_FaQ.setAutoscrolls(true);
        boton_FaQ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_FaQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_FaQActionPerformed(evt);
            }
        });
        BG.add(boton_FaQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, 30));

        boton_booking.setBackground(new java.awt.Color(51, 153, 0));
        boton_booking.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_booking.setForeground(new java.awt.Color(255, 255, 255));
        boton_booking.setText("Reservas");
        boton_booking.setToolTipText("");
        boton_booking.setAutoscrolls(true);
        boton_booking.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bookingActionPerformed(evt);
            }
        });
        BG.add(boton_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 30));

        boton_logout.setBackground(new java.awt.Color(51, 153, 0));
        boton_logout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_logout.setForeground(new java.awt.Color(255, 255, 255));
        boton_logout.setText("Cerrar sesion");
        boton_logout.setToolTipText("");
        boton_logout.setAutoscrolls(true);
        boton_logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoutActionPerformed(evt);
            }
        });
        BG.add(boton_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 130, 30));

        campo_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_questionActionPerformed(evt);
            }
        });
        BG.add(campo_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 430, 90));

        boton_allQuestion.setBackground(new java.awt.Color(51, 153, 0));
        boton_allQuestion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_allQuestion.setForeground(new java.awt.Color(255, 255, 255));
        boton_allQuestion.setText("Ver todo");
        boton_allQuestion.setToolTipText("");
        boton_allQuestion.setAutoscrolls(true);
        boton_allQuestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_allQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_allQuestionActionPerformed(evt);
            }
        });
        BG.add(boton_allQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 130, 30));

        boton_sendQuestion.setBackground(new java.awt.Color(51, 153, 0));
        boton_sendQuestion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_sendQuestion.setForeground(new java.awt.Color(255, 255, 255));
        boton_sendQuestion.setText("Enviar");
        boton_sendQuestion.setToolTipText("");
        boton_sendQuestion.setAutoscrolls(true);
        boton_sendQuestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_sendQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_sendQuestionActionPerformed(evt);
            }
        });
        BG.add(boton_sendQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 130, 30));

        boton_comoLlegar.setBackground(new java.awt.Color(51, 153, 0));
        boton_comoLlegar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_comoLlegar.setForeground(new java.awt.Color(255, 255, 255));
        boton_comoLlegar.setText("Acceso ");
        boton_comoLlegar.setToolTipText("");
        boton_comoLlegar.setAutoscrolls(true);
        boton_comoLlegar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_comoLlegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_comoLlegarActionPerformed(evt);
            }
        });
        BG.add(boton_comoLlegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 130, 30));

        boton_contacto.setBackground(new java.awt.Color(51, 153, 0));
        boton_contacto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_contacto.setForeground(new java.awt.Color(255, 255, 255));
        boton_contacto.setText("Contacto");
        boton_contacto.setToolTipText("");
        boton_contacto.setAutoscrolls(true);
        boton_contacto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_contactoActionPerformed(evt);
            }
        });
        BG.add(boton_contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 130, 30));

        boton_concepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        boton_concepto.setBorder(null);
        boton_concepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_conceptoActionPerformed(evt);
            }
        });
        BG.add(boton_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        boton_contacto1.setBackground(new java.awt.Color(51, 153, 0));
        boton_contacto1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_contacto1.setForeground(new java.awt.Color(255, 255, 255));
        boton_contacto1.setText("Desarrolladores");
        boton_contacto1.setToolTipText("");
        boton_contacto1.setAutoscrolls(true);
        boton_contacto1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_contacto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_contacto1ActionPerformed(evt);
            }
        });
        BG.add(boton_contacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 150, 30));

        TITULO.setBackground(new java.awt.Color(0, 0, 0));

        boton_myCuenta.setBackground(new java.awt.Color(0, 0, 0));
        boton_myCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accBla.png"))); // NOI18N
        boton_myCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_myCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_myCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_myCuentaActionPerformed(evt);
            }
        });

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Preguntas Frecuentes");
        titulo.setToolTipText("");

        javax.swing.GroupLayout TITULOLayout = new javax.swing.GroupLayout(TITULO);
        TITULO.setLayout(TITULOLayout);
        TITULOLayout.setHorizontalGroup(
            TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TITULOLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_myCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TITULOLayout.setVerticalGroup(
            TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TITULOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_myCuenta)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BG.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/FAq (1).jpg"))); // NOI18N
        BG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 640, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_productActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_productActionPerformed

    private void boton_salasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salasActionPerformed
        FMR_ROOMS newFrame = new FMR_ROOMS(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_salasActionPerformed

    private void boton_FaQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_FaQActionPerformed
        FMR_FaQ newFrame = new FMR_FaQ(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_FaQActionPerformed

    private void boton_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bookingActionPerformed
        FMR_BOOKING newFrame = new FMR_BOOKING(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_bookingActionPerformed

    private void boton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoutActionPerformed
        FMR_LOGIN newFrame = new FMR_LOGIN();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoutActionPerformed

    private void boton_allQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_allQuestionActionPerformed
        FMR_FaQ_AllQuestions newFrame = new FMR_FaQ_AllQuestions(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_allQuestionActionPerformed

    private void boton_sendQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_sendQuestionActionPerformed
        // Get the question from the text field
        String pregunta = campo_question.getText().trim();
        
        // Validate if the question is not empty
        if (pregunta.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor ingrese su pregunta",
                "Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            // Create a new FAQ with pending status
            FaQ newFaq = new FaQ(pregunta, "Solicitud pendiente de respuesta");
            newFaq.setPendiente(true);
            
            // Add the FAQ to the system
            faqController.addFaq(newFaq);
            
            // Show success message with tracking ID
            JOptionPane.showMessageDialog(this,
                "Pregunta enviada exitosamente.\nID de seguimiento: " + newFaq.getId(),
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Clear the question field
            campo_question.setText("");
            
        } catch (FaQException e) {
            JOptionPane.showMessageDialog(this,
                "Error al enviar la pregunta: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_sendQuestionActionPerformed

    private void boton_comoLlegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_comoLlegarActionPerformed
        try {
            Desktop.getDesktop().browse(new java.net.URI("https://maps.app.goo.gl/FgMJs7MVMYv9FcgB6")); // Replace with your actual coordinates
        } catch (IOException | URISyntaxException e) {
            JOptionPane.showMessageDialog(this,
                "Error al abrir el mapa: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_comoLlegarActionPerformed

    private void boton_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_contactoActionPerformed
        // Crear un panel personalizado para el JOptionPane
    JPanel contactPanel = new JPanel();
    contactPanel.setLayout(new BoxLayout(contactPanel, BoxLayout.Y_AXIS));
    contactPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
    
    // Estilo para los textos
    Font titleFont = new Font("Times New Roman", Font.BOLD, 18);
    Font infoFont = new Font("Times New Roman", Font.PLAIN, 16);
    
    // Título
    JLabel titleLabel = new JLabel("Información de Contacto");
    titleLabel.setFont(titleFont);
    titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
    
    // Teléfono
    JLabel phoneLabel = new JLabel("Teléfono: +591 65385455");
    phoneLabel.setFont(infoFont);
    phoneLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
    
    // Email
    JLabel emailLabel = new JLabel("Email: 202400347@est.umss.edu");
    emailLabel.setFont(infoFont);
    emailLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
    
    // Agregar componentes al panel
    contactPanel.add(titleLabel);
    contactPanel.add(Box.createRigidArea(new Dimension(0, 15)));
    contactPanel.add(phoneLabel);
    contactPanel.add(Box.createRigidArea(new Dimension(0, 10)));
    contactPanel.add(emailLabel);
    
    // Mostrar el JOptionPane con el panel personalizado
    JOptionPane.showMessageDialog(
        this,
        contactPanel,
        "Contacto",
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_boton_contactoActionPerformed

    private void boton_eventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eventsActionPerformed
        FMR_EVENT newFrame = new FMR_EVENT(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_eventsActionPerformed

    private void boton_conceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_conceptoActionPerformed
        FMR_CONCEPTO newFrame = new FMR_CONCEPTO(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_conceptoActionPerformed

    private void boton_contacto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_contacto1ActionPerformed
        FMR_DESARROLLADORES newFrame = new FMR_DESARROLLADORES(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_contacto1ActionPerformed

    private void campo_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_questionActionPerformed
        // add your handling code here:
    }//GEN-LAST:event_campo_questionActionPerformed

    private void boton_myCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_myCuentaActionPerformed
        FMR_MYACC newFrame = new FMR_MYACC(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_myCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_FaQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FMR_FaQ(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel TITULO;
    private javax.swing.JToggleButton boton_FaQ;
    private javax.swing.JToggleButton boton_allQuestion;
    private javax.swing.JToggleButton boton_booking;
    private javax.swing.JToggleButton boton_comoLlegar;
    private javax.swing.JButton boton_concepto;
    private javax.swing.JToggleButton boton_contacto;
    private javax.swing.JToggleButton boton_contacto1;
    private javax.swing.JToggleButton boton_events;
    private javax.swing.JToggleButton boton_logout;
    private javax.swing.JButton boton_myCuenta;
    private javax.swing.JToggleButton boton_product;
    private javax.swing.JToggleButton boton_salas;
    private javax.swing.JToggleButton boton_sendQuestion;
    private javax.swing.JTextField campo_question;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}