/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;
import model.*;

/**
 *
 * @author LENOVO
 */
public class FMR_PRODUCT extends javax.swing.JFrame {
    private final Account account;

    /**
     * Creates new form FMR_ProductosCategorias
     */
    public FMR_PRODUCT(Account account) {
        this.account = account;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_primarioProductos = new javax.swing.JPanel();
        boton_eventProductos = new javax.swing.JToggleButton();
        boton_productProductos = new javax.swing.JToggleButton();
        boton_salasProductos = new javax.swing.JToggleButton();
        boton_FaQProductos = new javax.swing.JToggleButton();
        boton_bookingProductos = new javax.swing.JToggleButton();
        boton_logoutProductos = new javax.swing.JToggleButton();
        boton_DisponibleProductos = new javax.swing.JToggleButton();
        boton_logoProductos = new javax.swing.JButton();
        boton_categoriasProductos = new javax.swing.JToggleButton();
        panel_tituloProductos = new javax.swing.JPanel();
        boton_perfilProductos = new javax.swing.JButton();
        label_tituloProductos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_primarioProductos.setBackground(new java.awt.Color(252, 240, 198));
        panel_primarioProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_primarioProductos.setRequestFocusEnabled(false);
        panel_primarioProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_eventProductos.setBackground(new java.awt.Color(51, 153, 0));
        boton_eventProductos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_eventProductos.setForeground(new java.awt.Color(255, 255, 255));
        boton_eventProductos.setText("Eventos");
        boton_eventProductos.setToolTipText("");
        boton_eventProductos.setAutoscrolls(true);
        boton_eventProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_eventProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eventProductosActionPerformed(evt);
            }
        });
        panel_primarioProductos.add(boton_eventProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        boton_productProductos.setBackground(new java.awt.Color(53, 101, 153));
        boton_productProductos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_productProductos.setForeground(new java.awt.Color(255, 255, 255));
        boton_productProductos.setText("Productos");
        boton_productProductos.setToolTipText("");
        boton_productProductos.setAutoscrolls(true);
        boton_productProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_productProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_productProductosActionPerformed(evt);
            }
        });
        panel_primarioProductos.add(boton_productProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 30));

        boton_salasProductos.setBackground(new java.awt.Color(51, 153, 0));
        boton_salasProductos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_salasProductos.setForeground(new java.awt.Color(255, 255, 255));
        boton_salasProductos.setText("Salas");
        boton_salasProductos.setToolTipText("");
        boton_salasProductos.setAutoscrolls(true);
        boton_salasProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_salasProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salasProductosActionPerformed(evt);
            }
        });
        panel_primarioProductos.add(boton_salasProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 30));

        boton_FaQProductos.setBackground(new java.awt.Color(51, 155, 0));
        boton_FaQProductos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_FaQProductos.setForeground(new java.awt.Color(255, 255, 255));
        boton_FaQProductos.setText("FaQ");
        boton_FaQProductos.setToolTipText("");
        boton_FaQProductos.setAutoscrolls(true);
        boton_FaQProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_FaQProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_FaQProductosActionPerformed(evt);
            }
        });
        panel_primarioProductos.add(boton_FaQProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, 30));

        boton_bookingProductos.setBackground(new java.awt.Color(51, 153, 0));
        boton_bookingProductos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_bookingProductos.setForeground(new java.awt.Color(255, 255, 255));
        boton_bookingProductos.setText("Reservas");
        boton_bookingProductos.setToolTipText("");
        boton_bookingProductos.setAutoscrolls(true);
        boton_bookingProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_bookingProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bookingProductosActionPerformed(evt);
            }
        });
        panel_primarioProductos.add(boton_bookingProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 30));

        boton_logoutProductos.setBackground(new java.awt.Color(51, 153, 0));
        boton_logoutProductos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_logoutProductos.setForeground(new java.awt.Color(255, 255, 255));
        boton_logoutProductos.setText("Cerrar sesion");
        boton_logoutProductos.setToolTipText("");
        boton_logoutProductos.setAutoscrolls(true);
        boton_logoutProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_logoutProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoutProductosActionPerformed(evt);
            }
        });
        panel_primarioProductos.add(boton_logoutProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 130, 30));

        boton_DisponibleProductos.setBackground(new java.awt.Color(51, 153, 0));
        boton_DisponibleProductos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_DisponibleProductos.setForeground(new java.awt.Color(255, 255, 255));
        boton_DisponibleProductos.setText("Ver Disponibles");
        boton_DisponibleProductos.setToolTipText("");
        boton_DisponibleProductos.setAutoscrolls(true);
        boton_DisponibleProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_DisponibleProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_DisponibleProductosActionPerformed(evt);
            }
        });
        panel_primarioProductos.add(boton_DisponibleProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 150, 30));

        boton_logoProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        boton_logoProductos.setBorder(null);
        boton_logoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoProductosActionPerformed(evt);
            }
        });
        panel_primarioProductos.add(boton_logoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        boton_categoriasProductos.setBackground(new java.awt.Color(51, 153, 0));
        boton_categoriasProductos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_categoriasProductos.setForeground(new java.awt.Color(255, 255, 255));
        boton_categoriasProductos.setText("Ver Categorias");
        boton_categoriasProductos.setToolTipText("");
        boton_categoriasProductos.setAutoscrolls(true);
        boton_categoriasProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_categoriasProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_categoriasProductosActionPerformed(evt);
            }
        });
        panel_primarioProductos.add(boton_categoriasProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 150, 30));

        panel_tituloProductos.setBackground(new java.awt.Color(0, 0, 0));

        boton_perfilProductos.setBackground(new java.awt.Color(0, 0, 0));
        boton_perfilProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accBla.png"))); // NOI18N
        boton_perfilProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_perfilProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_perfilProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_perfilProductosActionPerformed(evt);
            }
        });

        label_tituloProductos.setBackground(new java.awt.Color(0, 0, 0));
        label_tituloProductos.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        label_tituloProductos.setForeground(new java.awt.Color(255, 255, 255));
        label_tituloProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tituloProductos.setText("PRODUCTOS");
        label_tituloProductos.setToolTipText("");

        javax.swing.GroupLayout panel_tituloProductosLayout = new javax.swing.GroupLayout(panel_tituloProductos);
        panel_tituloProductos.setLayout(panel_tituloProductosLayout);
        panel_tituloProductosLayout.setHorizontalGroup(
            panel_tituloProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloProductosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label_tituloProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(boton_perfilProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_tituloProductosLayout.setVerticalGroup(
            panel_tituloProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_tituloProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_perfilProductos)
                    .addComponent(label_tituloProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_primarioProductos.add(panel_tituloProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cafeteria.png"))); // NOI18N
        panel_primarioProductos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 640, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_primarioProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_primarioProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        panel_primarioProductos.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_eventProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eventProductosActionPerformed
        FMR_EVENT newFrame = new FMR_EVENT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_eventProductosActionPerformed

    private void boton_productProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_productProductosActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_productProductosActionPerformed

    private void boton_salasProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salasProductosActionPerformed
        FMR_ROOMS newFrame = new FMR_ROOMS(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_salasProductosActionPerformed

    private void boton_FaQProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_FaQProductosActionPerformed
        FMR_FaQ newFrame = new FMR_FaQ(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_FaQProductosActionPerformed

    private void boton_bookingProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bookingProductosActionPerformed
        FMR_BOOKING newFrame = new FMR_BOOKING(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_bookingProductosActionPerformed

    private void boton_logoutProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoutProductosActionPerformed
        FMR_LOGIN newFrame = new FMR_LOGIN();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoutProductosActionPerformed

    private void boton_DisponibleProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_DisponibleProductosActionPerformed
        FMR_ProductosDisponibles newFrame = new FMR_ProductosDisponibles(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_DisponibleProductosActionPerformed

    private void boton_logoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoProductosActionPerformed
        FMR_CONCEPTO newFrame = new FMR_CONCEPTO(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoProductosActionPerformed

    private void boton_categoriasProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_categoriasProductosActionPerformed
        FMR_ProductosCategoria newFrame = new FMR_ProductosCategoria(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_categoriasProductosActionPerformed

    private void boton_perfilProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_perfilProductosActionPerformed
        FMR_MYACC newFrame = new FMR_MYACC(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_perfilProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMR_PRODUCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMR_PRODUCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMR_PRODUCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_PRODUCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMR_PRODUCT(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boton_DisponibleProductos;
    private javax.swing.JToggleButton boton_FaQProductos;
    private javax.swing.JToggleButton boton_bookingProductos;
    private javax.swing.JToggleButton boton_categoriasProductos;
    private javax.swing.JToggleButton boton_eventProductos;
    private javax.swing.JButton boton_logoProductos;
    private javax.swing.JToggleButton boton_logoutProductos;
    private javax.swing.JButton boton_perfilProductos;
    private javax.swing.JToggleButton boton_productProductos;
    private javax.swing.JToggleButton boton_salasProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_tituloProductos;
    private javax.swing.JPanel panel_primarioProductos;
    private javax.swing.JPanel panel_tituloProductos;
    // End of variables declaration//GEN-END:variables
}
