package view.gui;

//import controller.*;
//import exceptions.*;
import model.*;

//import javax.swing.*;
import java.awt.*;

/**
 * @author KNOWLES
 */
public class FMR_ProductosCategoria extends javax.swing.JFrame {
    private final Account account;
    /**
     * Creates new form FMR_PRODUCT
     */
    public FMR_ProductosCategoria(Account account) {
        this.account = account;
        Toolkit t=Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("/resources/logo.png")));
        setTitle("LEVELING_UP_LIFE");
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_primarioCategorias = new javax.swing.JPanel();
        boton_productCategorias = new javax.swing.JToggleButton();
        boton_salasCategorias = new javax.swing.JToggleButton();
        boton_FaQCategorias = new javax.swing.JToggleButton();
        boton_bookingCategorias = new javax.swing.JToggleButton();
        boton_logoutCategorias = new javax.swing.JToggleButton();
        boton_logoCategorias = new javax.swing.JButton();
        boton_comidasCategorias = new javax.swing.JToggleButton();
        boton_postresCategorias = new javax.swing.JToggleButton();
        boton_bebidasCategorias = new javax.swing.JToggleButton();
        boton_volverCategorias = new javax.swing.JToggleButton();
        boton_eventCategorias1 = new javax.swing.JToggleButton();
        label_fondoPCategorias = new javax.swing.JLabel();
        label_fondoBCategorias = new javax.swing.JLabel();
        panel_tituloCategorias = new javax.swing.JPanel();
        boton_perfilCategorias = new javax.swing.JButton();
        label_tituloCategorias = new javax.swing.JLabel();
        label_fondoCCategorias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_primarioCategorias.setBackground(new java.awt.Color(252, 240, 198));
        panel_primarioCategorias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_primarioCategorias.setRequestFocusEnabled(false);
        panel_primarioCategorias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_productCategorias.setBackground(new java.awt.Color(53, 101, 153));
        boton_productCategorias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_productCategorias.setForeground(new java.awt.Color(255, 255, 255));
        boton_productCategorias.setText("Productos");
        boton_productCategorias.setToolTipText("");
        boton_productCategorias.setAutoscrolls(true);
        boton_productCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_productCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_productCategoriasActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_productCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 30));

        boton_salasCategorias.setBackground(new java.awt.Color(51, 153, 0));
        boton_salasCategorias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_salasCategorias.setForeground(new java.awt.Color(255, 255, 255));
        boton_salasCategorias.setText("Salas");
        boton_salasCategorias.setToolTipText("");
        boton_salasCategorias.setAutoscrolls(true);
        boton_salasCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_salasCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salasCategoriasActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_salasCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 30));

        boton_FaQCategorias.setBackground(new java.awt.Color(51, 155, 0));
        boton_FaQCategorias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_FaQCategorias.setForeground(new java.awt.Color(255, 255, 255));
        boton_FaQCategorias.setText("FaQ");
        boton_FaQCategorias.setToolTipText("");
        boton_FaQCategorias.setAutoscrolls(true);
        boton_FaQCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_FaQCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_FaQCategoriasActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_FaQCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, 30));

        boton_bookingCategorias.setBackground(new java.awt.Color(51, 153, 0));
        boton_bookingCategorias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_bookingCategorias.setForeground(new java.awt.Color(255, 255, 255));
        boton_bookingCategorias.setText("Reservas");
        boton_bookingCategorias.setToolTipText("");
        boton_bookingCategorias.setAutoscrolls(true);
        boton_bookingCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_bookingCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bookingCategoriasActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_bookingCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 30));

        boton_logoutCategorias.setBackground(new java.awt.Color(51, 153, 0));
        boton_logoutCategorias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_logoutCategorias.setForeground(new java.awt.Color(255, 255, 255));
        boton_logoutCategorias.setText("Cerrar sesion");
        boton_logoutCategorias.setToolTipText("");
        boton_logoutCategorias.setAutoscrolls(true);
        boton_logoutCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_logoutCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoutCategoriasActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_logoutCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 130, 30));

        boton_logoCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        boton_logoCategorias.setBorder(null);
        boton_logoCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoCategoriasActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_logoCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        boton_comidasCategorias.setBackground(new java.awt.Color(51, 153, 0));
        boton_comidasCategorias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_comidasCategorias.setForeground(new java.awt.Color(255, 255, 255));
        boton_comidasCategorias.setText("COMIDAS");
        boton_comidasCategorias.setToolTipText("");
        boton_comidasCategorias.setAutoscrolls(true);
        boton_comidasCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_comidasCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_comidasCategoriasActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_comidasCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 150, 30));

        boton_postresCategorias.setBackground(new java.awt.Color(51, 153, 0));
        boton_postresCategorias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_postresCategorias.setForeground(new java.awt.Color(255, 255, 255));
        boton_postresCategorias.setText("POSTRES");
        boton_postresCategorias.setToolTipText("");
        boton_postresCategorias.setAutoscrolls(true);
        boton_postresCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_postresCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_postresCategoriasActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_postresCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 150, 30));

        boton_bebidasCategorias.setBackground(new java.awt.Color(51, 153, 0));
        boton_bebidasCategorias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_bebidasCategorias.setForeground(new java.awt.Color(255, 255, 255));
        boton_bebidasCategorias.setText("BEBIDAS");
        boton_bebidasCategorias.setToolTipText("");
        boton_bebidasCategorias.setAutoscrolls(true);
        boton_bebidasCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_bebidasCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bebidasCategoriasActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_bebidasCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 150, 30));

        boton_volverCategorias.setBackground(new java.awt.Color(51, 153, 0));
        boton_volverCategorias.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_volverCategorias.setForeground(new java.awt.Color(255, 255, 255));
        boton_volverCategorias.setText("Volver");
        boton_volverCategorias.setToolTipText("");
        boton_volverCategorias.setAutoscrolls(true);
        boton_volverCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_volverCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverCategoriasActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_volverCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 130, 30));

        boton_eventCategorias1.setBackground(new java.awt.Color(51, 153, 0));
        boton_eventCategorias1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_eventCategorias1.setForeground(new java.awt.Color(255, 255, 255));
        boton_eventCategorias1.setText("Eventos");
        boton_eventCategorias1.setToolTipText("");
        boton_eventCategorias1.setAutoscrolls(true);
        boton_eventCategorias1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_eventCategorias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eventCategorias1ActionPerformed(evt);
            }
        });
        panel_primarioCategorias.add(boton_eventCategorias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        label_fondoPCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/postre1.png"))); // NOI18N
        panel_primarioCategorias.add(label_fondoPCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 210, 420));

        label_fondoBCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bebida1.png"))); // NOI18N
        panel_primarioCategorias.add(label_fondoBCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 220, 420));

        panel_tituloCategorias.setBackground(new java.awt.Color(0, 0, 0));

        boton_perfilCategorias.setBackground(new java.awt.Color(0, 0, 0));
        boton_perfilCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accBla.png"))); // NOI18N
        boton_perfilCategorias.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_perfilCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_perfilCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_perfilCategoriasActionPerformed(evt);
            }
        });

        label_tituloCategorias.setBackground(new java.awt.Color(0, 0, 0));
        label_tituloCategorias.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        label_tituloCategorias.setForeground(new java.awt.Color(255, 255, 255));
        label_tituloCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tituloCategorias.setText("Categorias");
        label_tituloCategorias.setToolTipText("");

        javax.swing.GroupLayout panel_tituloCategoriasLayout = new javax.swing.GroupLayout(panel_tituloCategorias);
        panel_tituloCategorias.setLayout(panel_tituloCategoriasLayout);
        panel_tituloCategoriasLayout.setHorizontalGroup(
            panel_tituloCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloCategoriasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label_tituloCategorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(boton_perfilCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_tituloCategoriasLayout.setVerticalGroup(
            panel_tituloCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloCategoriasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_tituloCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_perfilCategorias)
                    .addComponent(label_tituloCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_primarioCategorias.add(panel_tituloCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 100));

        label_fondoCCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/comida1.png"))); // NOI18N
        panel_primarioCategorias.add(label_fondoCCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 210, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_primarioCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_primarioCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_productCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_productCategoriasActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_productCategoriasActionPerformed

    private void boton_salasCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salasCategoriasActionPerformed
        FMR_ROOMS newFrame = new FMR_ROOMS(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_salasCategoriasActionPerformed

    private void boton_FaQCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_FaQCategoriasActionPerformed
        FMR_FaQ newFrame = new FMR_FaQ(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_FaQCategoriasActionPerformed

    private void boton_bookingCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bookingCategoriasActionPerformed
        FMR_BOOKING newFrame = new FMR_BOOKING(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_bookingCategoriasActionPerformed

    private void boton_logoutCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoutCategoriasActionPerformed
        FMR_LOGIN newFrame = new FMR_LOGIN();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoutCategoriasActionPerformed

    private void boton_comidasCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_comidasCategoriasActionPerformed
        FMR_ProductosComida newFrame = new FMR_ProductosComida(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_comidasCategoriasActionPerformed

    private void boton_logoCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoCategoriasActionPerformed
        FMR_CONCEPTO newFrame = new FMR_CONCEPTO(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoCategoriasActionPerformed

    private void boton_postresCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_postresCategoriasActionPerformed
        FMR_ProductosPostre newFrame = new FMR_ProductosPostre(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_postresCategoriasActionPerformed

    private void boton_perfilCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_perfilCategoriasActionPerformed
        FMR_MYACC newFrame = new FMR_MYACC(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_perfilCategoriasActionPerformed

    private void boton_bebidasCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bebidasCategoriasActionPerformed
        FMR_ProductosBebida newFrame = new FMR_ProductosBebida(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_bebidasCategoriasActionPerformed

    private void boton_volverCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverCategoriasActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_volverCategoriasActionPerformed

    private void boton_eventCategorias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eventCategorias1ActionPerformed
        FMR_EVENT newFrame = new FMR_EVENT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_eventCategorias1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMR_ProductosCategoria(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boton_FaQCategorias;
    private javax.swing.JToggleButton boton_bebidasCategorias;
    private javax.swing.JToggleButton boton_bookingCategorias;
    private javax.swing.JToggleButton boton_comidasCategorias;
    private javax.swing.JToggleButton boton_eventCategorias1;
    private javax.swing.JButton boton_logoCategorias;
    private javax.swing.JToggleButton boton_logoutCategorias;
    private javax.swing.JButton boton_perfilCategorias;
    private javax.swing.JToggleButton boton_postresCategorias;
    private javax.swing.JToggleButton boton_productCategorias;
    private javax.swing.JToggleButton boton_salasCategorias;
    private javax.swing.JToggleButton boton_volverCategorias;
    private javax.swing.JLabel label_fondoBCategorias;
    private javax.swing.JLabel label_fondoCCategorias;
    private javax.swing.JLabel label_fondoPCategorias;
    private javax.swing.JLabel label_tituloCategorias;
    private javax.swing.JPanel panel_primarioCategorias;
    private javax.swing.JPanel panel_tituloCategorias;
    // End of variables declaration//GEN-END:variables
}
