package view.gui;

import controller.*;
import exceptions.*;
import model.*;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author KNKOW-RIC
 */
public class FMR_RECUPERACION extends javax.swing.JFrame {
    private final AccountController accountController;
    /**
     * Creates new form FMR_RECUPERACION
     */
    public FMR_RECUPERACION() {
        AccountController tempController;
        try {
            tempController = new AccountController(new FileHandler<>(new Account()));
        } catch (AccountException e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.accountController = tempController;
        initComponents();
        setLocationRelativeTo(null);
        setupPlaceholders();
    }

    private void setupPlaceholders() {
        // Usuario
        campo_user2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (campo_user2.getText().trim().equals("Nombre de usuario")) {
                    campo_user2.setText("");
                    campo_user2.setForeground(new Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (campo_user2.getText().isEmpty()) {
                    campo_user2.setText("Nombre de usuario");
                    campo_user2.setForeground(new Color(102, 102, 102));
                }
            }
        });

        // Teléfono
        campo_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (campo_user.getText().trim().equals("Telefono")) {
                    campo_user.setText("");
                    campo_user.setForeground(new Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (campo_user.getText().isEmpty()) {
                    campo_user.setText("Telefono");
                    campo_user.setForeground(new Color(102, 102, 102));
                }
            }
        });

        // Email
        campo_user1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (campo_user1.getText().trim().equals("Direccion de correo electronico")) {
                    campo_user1.setText("");
                    campo_user1.setForeground(new Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (campo_user1.getText().isEmpty()) {
                    campo_user1.setText("Direccion de correo electronico");
                    campo_user1.setForeground(new Color(102, 102, 102));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        campo_user = new javax.swing.JTextField();
        user_separator = new javax.swing.JSeparator();
        pass_separator = new javax.swing.JSeparator();
        campo_user1 = new javax.swing.JTextField();
        user_separator1 = new javax.swing.JSeparator();
        campo_user2 = new javax.swing.JTextField();
        buton_volver = new javax.swing.JToggleButton();
        buton_solicitar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEVELING");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(252, 240, 198));
        setFocusCycleRoot(false);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(400, 580));
        setSize(new java.awt.Dimension(400, 580));

        BG.setBackground(new java.awt.Color(252, 240, 198));
        BG.setMinimumSize(new java.awt.Dimension(800, 500));
        BG.setPreferredSize(new java.awt.Dimension(400, 580));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        BG.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, 150));

        titulo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titulo1.setText("¿TIENE PROBLEMAS PARA INICIAR SESION?");
        BG.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 320, -1));

        titulo2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        titulo2.setText("Ingresa tu nombre usuario, telefono, correo y \nrestableceremos tu contraseña");
        BG.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 370, 30));

        campo_user.setBackground(new java.awt.Color(252, 240, 198));
        campo_user.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campo_user.setForeground(new java.awt.Color(102, 102, 102));
        campo_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_user.setText("Telefono");
        campo_user.setBorder(null);
        campo_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_userActionPerformed(evt);
            }
        });
        BG.add(campo_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 260, 30));

        user_separator.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(user_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 260, 10));

        pass_separator.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(pass_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 260, 10));

        campo_user1.setBackground(new java.awt.Color(252, 240, 198));
        campo_user1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campo_user1.setForeground(new java.awt.Color(102, 102, 102));
        campo_user1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_user1.setText("Direccion de correo electronico");
        campo_user1.setBorder(null);
        campo_user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_user1ActionPerformed(evt);
            }
        });
        BG.add(campo_user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 260, 30));

        user_separator1.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(user_separator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 260, 10));

        campo_user2.setBackground(new java.awt.Color(252, 240, 198));
        campo_user2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campo_user2.setForeground(new java.awt.Color(102, 102, 102));
        campo_user2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_user2.setText(" Nombre de usuario");
        campo_user2.setBorder(null);
        campo_user2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_user2ActionPerformed(evt);
            }
        });
        BG.add(campo_user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 260, 30));

        buton_volver.setBackground(new java.awt.Color(51, 153, 0));
        buton_volver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buton_volver.setForeground(new java.awt.Color(255, 255, 255));
        buton_volver.setText("Volver");
        buton_volver.setToolTipText("");
        buton_volver.setAutoscrolls(true);
        buton_volver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_volverActionPerformed(evt);
            }
        });
        BG.add(buton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 130, 30));

        buton_solicitar.setBackground(new java.awt.Color(51, 153, 0));
        buton_solicitar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buton_solicitar.setForeground(new java.awt.Color(255, 255, 255));
        buton_solicitar.setText("Solicitar");
        buton_solicitar.setToolTipText("");
        buton_solicitar.setAutoscrolls(true);
        buton_solicitar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buton_solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_solicitarActionPerformed(evt);
            }
        });
        BG.add(buton_solicitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_userActionPerformed(java.awt.event.ActionEvent evt) {}

    private void buton_volverActionPerformed(java.awt.event.ActionEvent evt) {                                             
        FMR_LOGIN newFrame = new FMR_LOGIN(); 
        newFrame.setVisible(true);
        this.dispose();
    }

    private void campo_user1ActionPerformed(java.awt.event.ActionEvent evt) {}

    private void campo_user2ActionPerformed(java.awt.event.ActionEvent evt) {}

    private void buton_solicitarActionPerformed(java.awt.event.ActionEvent evt) {
        String username = campo_user2.getText().trim();
        String phone = campo_user.getText().trim();
        String email = campo_user1.getText().trim();

        try {
            Account account = accountController.getByUsername(username);
            
            if (account != null && 
                account.getPhone().equals(phone) && 
                account.getEmail().equals(email)) {
                
                accountController.resetUserPassword(username, "L3V3L1NG_up_L1F3");
                
                // Configuración global para todos los diálogos
                UIManager.put("OptionPane.messageForeground", Color.BLACK);
                UIManager.put("Button.foreground", Color.BLACK);
                UIManager.put("Button.font", new Font("Times New Roman", Font.BOLD, 12));
                
                // Diálogo de éxito
                JPanel panel = new JPanel();
                JLabel label = new JLabel("Recuperación Exitosa");
                label.setFont(new Font("Times New Roman", Font.BOLD, 18));
                label.setHorizontalAlignment(SwingConstants.CENTER);
                panel.add(label);
                
                JOptionPane.showMessageDialog(
                    this,
                    panel,
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
                );
                
                // Diálogo de contraseña
                JPanel passPanel = new JPanel();
                JLabel passLabel = new JLabel("<html>Su nueva contraseña es:<br>'L3V3L1NG_up_L1F3'</html>");
                passLabel.setFont(new Font("Times New Roman", Font.BOLD, 14));
                passPanel.add(passLabel);
                
                JOptionPane.showMessageDialog(
                    this,
                    passPanel,
                    "Contraseña Temporal",
                    JOptionPane.INFORMATION_MESSAGE
                );
                
                FMR_LOGIN loginFrame = new FMR_LOGIN();
                loginFrame.setVisible(true);
                this.dispose();
                
            } else {
                // Diálogo de error
                JPanel errorPanel = new JPanel();
                JLabel errorLabel = new JLabel("Los datos ingresados no coinciden con ninguna cuenta");
                errorLabel.setFont(new Font("Times New Roman", Font.BOLD, 14));
                errorPanel.add(errorLabel);
                
                JOptionPane.showMessageDialog(
                    this,
                    errorPanel,
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        } catch (AccountException e) {
            JPanel errorPanel = new JPanel();
            JLabel errorLabel = new JLabel("Error: " + e.getMessage());
            errorLabel.setFont(new Font("Times New Roman", Font.BOLD, 14));
            errorPanel.add(errorLabel);
            
            JOptionPane.showMessageDialog(
                this,
                errorPanel,
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FMR_LOGIN().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JToggleButton buton_solicitar;
    private javax.swing.JToggleButton buton_volver;
    private javax.swing.JTextField campo_user;
    private javax.swing.JTextField campo_user1;
    private javax.swing.JTextField campo_user2;
    private javax.swing.JLabel logo;
    private javax.swing.JSeparator pass_separator;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JSeparator user_separator;
    private javax.swing.JSeparator user_separator1;
    // End of variables declaration//GEN-END:variables
}
