package view.gui;

import controller.*;
import exceptions.*;
import model.*;

import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.util.List;

/**
 * @author DAVID FT KNOWLES
 */
public class FMR_B_HIST extends javax.swing.JFrame {
    private final Account account;
    private final BookingController bookingController;
    private final RoomController roomController;

    public FMR_B_HIST(Account account) {
        // Inicialización de controllers
        BookingController tempController;
        RoomController tempRoomController;
        try {
            tempRoomController = new RoomController(new FileHandler<>(new Room()));
            tempController = new BookingController(new FileHandler<>(new Booking()), tempRoomController);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            tempRoomController = null;
            System.exit(1);
        }
        this.bookingController = tempController;
        this.roomController = tempRoomController;
        this.account = account;
    
        initComponents();
        setLocationRelativeTo(null);
        loadBookingsToTable();
    
        // --- Configuración visual de la tabla ---
        jTable2.setOpaque(true);
        jTable2.setBackground(new Color(255,255,255,200)); // Fondo totalmente transparente
        jTable2.setFillsViewportHeight(true);
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);

        BG.remove(jScrollPane2);
        BG.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 580, 330));
    
        BG.setComponentZOrder(jScrollPane2, 0); // Primer plano
        BG.setComponentZOrder(boton_volver,1);
        BG.setComponentZOrder(jLabel1, 2);      // Fondo
    
        jTable2.setForeground(Color.BLACK);
        jTable2.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        jTable2.setShowGrid(false); // Opcional: eliminar líneas de la grilla
    
        BG.revalidate();
        BG.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        boton_volver = new javax.swing.JToggleButton();
        TITULO = new javax.swing.JPanel();
        boton_myCuenta = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        boton_product = new javax.swing.JToggleButton();
        boton_salas = new javax.swing.JToggleButton();
        boton_FaQ = new javax.swing.JToggleButton();
        boton_booking = new javax.swing.JToggleButton();
        boton_concepto = new javax.swing.JButton();
        boton_events1 = new javax.swing.JToggleButton();
        boton_cerrarS = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(875, 555));

        BG.setBackground(new java.awt.Color(252, 240, 198));
        BG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BG.setMinimumSize(new java.awt.Dimension(860, 520));
        BG.setPreferredSize(new java.awt.Dimension(860, 520));
        BG.setRequestFocusEnabled(false);
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_volver.setBackground(new java.awt.Color(51, 153, 0));
        boton_volver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_volver.setForeground(new java.awt.Color(255, 255, 255));
        boton_volver.setText("Volver");
        boton_volver.setToolTipText("");
        boton_volver.setAutoscrolls(true);
        boton_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverActionPerformed(evt);
            }
        });
        BG.add(boton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 130, 30));

        TITULO.setBackground(new java.awt.Color(0, 0, 0));

        boton_myCuenta.setBackground(new java.awt.Color(0, 0, 0));
        boton_myCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accBla.png"))); // NOI18N
        boton_myCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_myCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_myCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_myCuentaActionPerformed(evt);
            }
        });

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Historial de Reservas");
        titulo.setToolTipText("");

        javax.swing.GroupLayout TITULOLayout = new javax.swing.GroupLayout(TITULO);
        TITULO.setLayout(TITULOLayout);
        TITULOLayout.setHorizontalGroup(
            TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TITULOLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_myCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        TITULOLayout.setVerticalGroup(
            TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TITULOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TITULOLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(boton_myCuenta)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        BG.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 100));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Reservas", "ID Usuario", "ID Habitacion", "Inicio", "Fin", "Horas", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        BG.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 580, 330));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rooms.jpg"))); // NOI18N
        BG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 640, 420));

        boton_product.setBackground(new java.awt.Color(51, 153, 0));
        boton_product.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_product.setForeground(new java.awt.Color(255, 255, 255));
        boton_product.setText("Productos");
        boton_product.setToolTipText("");
        boton_product.setAutoscrolls(true);
        boton_product.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_productActionPerformed(evt);
            }
        });
        BG.add(boton_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 130, 30));

        boton_salas.setBackground(new java.awt.Color(51, 153, 0));
        boton_salas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_salas.setForeground(new java.awt.Color(255, 255, 255));
        boton_salas.setText("Salas");
        boton_salas.setToolTipText("");
        boton_salas.setAutoscrolls(true);
        boton_salas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_salas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salasActionPerformed(evt);
            }
        });
        BG.add(boton_salas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 130, 30));

        boton_FaQ.setBackground(new java.awt.Color(0, 153, 0));
        boton_FaQ.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_FaQ.setForeground(new java.awt.Color(255, 255, 255));
        boton_FaQ.setText("FaQ");
        boton_FaQ.setToolTipText("");
        boton_FaQ.setAutoscrolls(true);
        boton_FaQ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_FaQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_FaQActionPerformed(evt);
            }
        });
        BG.add(boton_FaQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 130, 30));

        boton_booking.setBackground(new java.awt.Color(43, 101, 153));
        boton_booking.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_booking.setForeground(new java.awt.Color(255, 255, 255));
        boton_booking.setText("Reservas");
        boton_booking.setToolTipText("");
        boton_booking.setAutoscrolls(true);
        boton_booking.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bookingActionPerformed(evt);
            }
        });
        BG.add(boton_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 130, 30));

        boton_concepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        boton_concepto.setBorder(null);
        boton_concepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_conceptoActionPerformed(evt);
            }
        });
        BG.add(boton_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        boton_events1.setBackground(new java.awt.Color(51, 153, 0));
        boton_events1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_events1.setForeground(new java.awt.Color(255, 255, 255));
        boton_events1.setText("Eventos");
        boton_events1.setToolTipText("");
        boton_events1.setAutoscrolls(true);
        boton_events1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_events1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_events1ActionPerformed(evt);
            }
        });
        BG.add(boton_events1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 30));

        boton_cerrarS.setBackground(new java.awt.Color(51, 153, 0));
        boton_cerrarS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_cerrarS.setForeground(new java.awt.Color(255, 255, 255));
        boton_cerrarS.setText("Cerrar sesion");
        boton_cerrarS.setToolTipText("");
        boton_cerrarS.setAutoscrolls(true);
        boton_cerrarS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_cerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cerrarSActionPerformed(evt);
            }
        });
        BG.add(boton_cerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverActionPerformed
       FMR_BOOKING newFrame = new FMR_BOOKING(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_volverActionPerformed

    private void boton_myCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_myCuentaActionPerformed
        FMR_MYACC newFrame = new FMR_MYACC(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_myCuentaActionPerformed

    private void boton_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_productActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_productActionPerformed

    private void boton_salasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salasActionPerformed
        FMR_ROOMS newFrame = new FMR_ROOMS(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_salasActionPerformed

    private void boton_FaQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_FaQActionPerformed
        FMR_FaQ newFrame = new FMR_FaQ(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_FaQActionPerformed

    private void boton_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bookingActionPerformed
        FMR_BOOKING newFrame = new FMR_BOOKING(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_bookingActionPerformed

    private void boton_conceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_conceptoActionPerformed
        FMR_CONCEPTO newFrame = new FMR_CONCEPTO(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_conceptoActionPerformed

    private void boton_events1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_events1ActionPerformed
        FMR_B_Crear newFrame = new FMR_B_Crear(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_events1ActionPerformed

    private void boton_cerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cerrarSActionPerformed
        FMR_LOGIN newFrame = new FMR_LOGIN();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_cerrarSActionPerformed

    private void loadBookingsToTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            
            model.setColumnIdentifiers(new String[]{ 
                "Sala", 
                "Fecha Inicio", 
                "Fecha Fin", 
                "Horas", 
                "Total"
            });
            model.setRowCount(0);
    
            List<Booking> allBookings = bookingController.getAllBookings();
            if (allBookings.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "No hay reservas registradas",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }
    
            for (Booking booking : allBookings) {
                if (booking.getAccountId().equals(account.getId())) {
                    // Get room name
                    String roomName = "Desconocido";
                    try {
                        Room room = roomController.getRoomById(booking.getRoomId());
                        if (room != null) {
                            roomName = room.getNombre() + " (" + getTipoHabitacion(room.getTipo()) + ")";
                        }
                    } catch (Exception e) {
                        // If room not found, keep default name
                    }
                    
                    model.addRow(new Object[]{
                        roomName,
                        booking.getFechaInicio().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")),
                        booking.getFechaFin().format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm")),
                        booking.getHoras(),
                        String.format("$%.2f", booking.getTotal())
                    });
                }
            }
    
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,
                    "No tienes reservas registradas",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }
    
            // Adjust column widths
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(180);  // Sala (increased for name + type)
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(120);  // Fecha Inicio
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(120);  // Fecha Fin
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(80);   // Horas
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(80);   // Total
            
            // Adjust table size and position
            BG.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 520, 330));
    
            // Center align all columns
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            for (int i = 0; i < jTable2.getColumnCount(); i++) {
                jTable2.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
            }
    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar reservas: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    // Método auxiliar para convertir tipo de habitación (char) a descripción
    private String getTipoHabitacion(char tipo) {
        switch(tipo) {
            case 'I': return "Individual";
            case 'P': return "Privada";
            case 'D': return "Dormitorio";
            case 'M': return "Mixta";
            default: return "Desconocido";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_B_HIST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FMR_B_HIST(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel TITULO;
    private javax.swing.JToggleButton boton_FaQ;
    private javax.swing.JToggleButton boton_booking;
    private javax.swing.JToggleButton boton_cerrarS;
    private javax.swing.JButton boton_concepto;
    private javax.swing.JToggleButton boton_events1;
    private javax.swing.JButton boton_myCuenta;
    private javax.swing.JToggleButton boton_product;
    private javax.swing.JToggleButton boton_salas;
    private javax.swing.JToggleButton boton_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}