/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;
import controller.*;
import exceptions.*;
import model.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.net.URISyntaxException;

/**
 *
 * @author LENOVO
 */
public class FMR_ProductosBebida extends javax.swing.JFrame {
    private final Account account;
    private final ProductController productController;
    /**
     * Creates new form FMR_ProductosBebida
     * @param account
     */
    public FMR_ProductosBebida(Account account) {
        ProductController tempController;
        try {
            tempController = new ProductController(new FileHandler<>(new Product()));
        } catch (ProductException e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.
                productController = tempController;
        this.account = account;
        initComponents();
        setLocationRelativeTo(null);
        loadActiveProducts(); // Llamar después de initComponents()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_primarioBebidas = new javax.swing.JPanel();
        boton_comprarBebidas = new javax.swing.JToggleButton();
        boton_productBebidas = new javax.swing.JToggleButton();
        boton_salasBebidas = new javax.swing.JToggleButton();
        boton_FaQBebidas = new javax.swing.JToggleButton();
        boton_bookingBebidas = new javax.swing.JToggleButton();
        boton_logoutBebidas = new javax.swing.JToggleButton();
        boton_volverBebidas = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Bebidas = new javax.swing.JTable();
        boton_logoBebidas = new javax.swing.JButton();
        boton_eventBebidas = new javax.swing.JToggleButton();
        panel_tituloBebidas = new javax.swing.JPanel();
        boton_perfilBebidas = new javax.swing.JButton();
        label_tituloBebidas = new javax.swing.JLabel();
        label_fondoBebidas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_primarioBebidas.setBackground(new java.awt.Color(252, 240, 198));
        panel_primarioBebidas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_primarioBebidas.setRequestFocusEnabled(false);
        panel_primarioBebidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_comprarBebidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_comprarBebidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_comprarBebidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_comprarBebidas.setText("Comprar");
        boton_comprarBebidas.setToolTipText("");
        boton_comprarBebidas.setAutoscrolls(true);
        boton_comprarBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_comprarBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_comprarBebidasActionPerformed(evt);
            }
        });
        panel_primarioBebidas.add(boton_comprarBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 130, 30));

        boton_productBebidas.setBackground(new java.awt.Color(53, 101, 153));
        boton_productBebidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_productBebidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_productBebidas.setText("Productos");
        boton_productBebidas.setToolTipText("");
        boton_productBebidas.setAutoscrolls(true);
        boton_productBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_productBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_productBebidasActionPerformed(evt);
            }
        });
        panel_primarioBebidas.add(boton_productBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 30));

        boton_salasBebidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_salasBebidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_salasBebidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_salasBebidas.setText("Salas");
        boton_salasBebidas.setToolTipText("");
        boton_salasBebidas.setAutoscrolls(true);
        boton_salasBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_salasBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salasBebidasActionPerformed(evt);
            }
        });
        panel_primarioBebidas.add(boton_salasBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 30));

        boton_FaQBebidas.setBackground(new java.awt.Color(51, 155, 0));
        boton_FaQBebidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_FaQBebidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_FaQBebidas.setText("FaQ");
        boton_FaQBebidas.setToolTipText("");
        boton_FaQBebidas.setAutoscrolls(true);
        boton_FaQBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_FaQBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_FaQBebidasActionPerformed(evt);
            }
        });
        panel_primarioBebidas.add(boton_FaQBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, 30));

        boton_bookingBebidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_bookingBebidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_bookingBebidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_bookingBebidas.setText("Reservas");
        boton_bookingBebidas.setToolTipText("");
        boton_bookingBebidas.setAutoscrolls(true);
        boton_bookingBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_bookingBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bookingBebidasActionPerformed(evt);
            }
        });
        panel_primarioBebidas.add(boton_bookingBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 30));

        boton_logoutBebidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_logoutBebidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_logoutBebidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_logoutBebidas.setText("Cerrar sesion");
        boton_logoutBebidas.setToolTipText("");
        boton_logoutBebidas.setAutoscrolls(true);
        boton_logoutBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_logoutBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoutBebidasActionPerformed(evt);
            }
        });
        panel_primarioBebidas.add(boton_logoutBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 130, 30));

        boton_volverBebidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_volverBebidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_volverBebidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_volverBebidas.setText("Volver");
        boton_volverBebidas.setToolTipText("");
        boton_volverBebidas.setAutoscrolls(true);
        boton_volverBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_volverBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverBebidasActionPerformed(evt);
            }
        });
        panel_primarioBebidas.add(boton_volverBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 150, 30));

        tabla_Bebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CATEGORIA", "PRECIO", "STOCK"
            }
        ));
        jScrollPane1.setViewportView(tabla_Bebidas);

        panel_primarioBebidas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 560, 340));

        boton_logoBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        boton_logoBebidas.setBorder(null);
        boton_logoBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoBebidasActionPerformed(evt);
            }
        });
        panel_primarioBebidas.add(boton_logoBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        boton_eventBebidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_eventBebidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_eventBebidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_eventBebidas.setText("Eventos");
        boton_eventBebidas.setToolTipText("");
        boton_eventBebidas.setAutoscrolls(true);
        boton_eventBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_eventBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eventBebidasActionPerformed(evt);
            }
        });
        panel_primarioBebidas.add(boton_eventBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        panel_tituloBebidas.setBackground(new java.awt.Color(0, 0, 0));

        boton_perfilBebidas.setBackground(new java.awt.Color(0, 0, 0));
        boton_perfilBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accBla.png"))); // NOI18N
        boton_perfilBebidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_perfilBebidas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_perfilBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_perfilBebidasActionPerformed(evt);
            }
        });

        label_tituloBebidas.setBackground(new java.awt.Color(0, 0, 0));
        label_tituloBebidas.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        label_tituloBebidas.setForeground(new java.awt.Color(255, 255, 255));
        label_tituloBebidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tituloBebidas.setText("BEBIDAS");
        label_tituloBebidas.setToolTipText("");

        javax.swing.GroupLayout panel_tituloBebidasLayout = new javax.swing.GroupLayout(panel_tituloBebidas);
        panel_tituloBebidas.setLayout(panel_tituloBebidasLayout);
        panel_tituloBebidasLayout.setHorizontalGroup(
            panel_tituloBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloBebidasLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(label_tituloBebidas)
                .addGap(124, 124, 124)
                .addComponent(boton_perfilBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_tituloBebidasLayout.setVerticalGroup(
            panel_tituloBebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloBebidasLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(boton_perfilBebidas)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloBebidasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_tituloBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_primarioBebidas.add(panel_tituloBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 100));

        label_fondoBebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/categoriaComida.png"))); // NOI18N
        panel_primarioBebidas.add(label_fondoBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 640, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_primarioBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_primarioBebidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_comprarBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_comprarBebidasActionPerformed
            int selectedRow = tabla_Bebidas.getSelectedRow();
            if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, seleccione un producto para comprar", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
            }
    
        // Obtener datos del producto
        String productId = tabla_Bebidas.getValueAt(selectedRow, 0).toString();
        String productName = tabla_Bebidas.getValueAt(selectedRow, 1).toString();
        double precio = Double.parseDouble(tabla_Bebidas.getValueAt(selectedRow, 3).toString());
        int stock = Integer.parseInt(tabla_Bebidas.getValueAt(selectedRow, 4).toString());
    
        // Panel de compra
        JPanel panel = new JPanel(new GridLayout(3, 2));
        JSpinner cantidadSpinner = new JSpinner(new SpinnerNumberModel(1, 1, stock, 1));
        
        panel.add(new JLabel("Producto:"));
        panel.add(new JLabel(productName));
        panel.add(new JLabel("Precio unitario:"));
        panel.add(new JLabel("$" + precio));
        panel.add(new JLabel("Cantidad (Máx: " + stock + "):"));
        panel.add(cantidadSpinner);
        
        int result = JOptionPane.showConfirmDialog(
            this, 
            panel, 
            "Confirmar Compra", 
            JOptionPane.OK_CANCEL_OPTION, 
            JOptionPane.PLAIN_MESSAGE);
        
        if (result == JOptionPane.OK_OPTION) {
            try {
                int cantidad = (int) cantidadSpinner.getValue();
                double total = precio * cantidad;
                
                // Actualizar stock (asumiendo que productController tiene este método)
                productController.updateStock(productId, cantidad);
                
                JOptionPane.showMessageDialog(this, 
                    "Compra realizada!\n" +
                    "Producto: " + productName + "\n" +
                    "Cantidad: " + cantidad + "\n" +
                    "Total: $" + total,
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Actualizar tabla
                loadActiveProducts();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, 
                    "Error al comprar: " + e.getMessage(), 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_boton_comprarBebidasActionPerformed

    private void boton_productBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_productBebidasActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_productBebidasActionPerformed

    private void boton_salasBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salasBebidasActionPerformed
        FMR_ROOMS newFrame = new FMR_ROOMS(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_salasBebidasActionPerformed

    private void boton_FaQBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_FaQBebidasActionPerformed
        FMR_FaQ newFrame = new FMR_FaQ(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_FaQBebidasActionPerformed

    private void boton_bookingBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bookingBebidasActionPerformed
        FMR_BOOKING newFrame = new FMR_BOOKING(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_bookingBebidasActionPerformed

    private void boton_logoutBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoutBebidasActionPerformed
        FMR_LOGIN newFrame = new FMR_LOGIN();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoutBebidasActionPerformed

    private void boton_volverBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverBebidasActionPerformed
        FMR_ProductosCategoria newFrame = new FMR_ProductosCategoria(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_volverBebidasActionPerformed

    private void boton_logoBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoBebidasActionPerformed
        FMR_CONCEPTO newFrame = new FMR_CONCEPTO(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoBebidasActionPerformed

    private void boton_eventBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eventBebidasActionPerformed
        FMR_EVENT newFrame = new FMR_EVENT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_eventBebidasActionPerformed

    private void boton_perfilBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_perfilBebidasActionPerformed
        FMR_MYACC newFrame = new FMR_MYACC(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_perfilBebidasActionPerformed
    
    private void loadActiveProducts() {
        try {
        // Obtener productos disponibles del controlador
        List<Product> availableProducts = productController.getAvailableProducts();
        
        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tabla_Bebidas.getModel();
        model.setRowCount(0); // Limpiar la tabla
        
        // Filtrar solo productos de categoría 'C' y llenar la tabla
        for (Product product : availableProducts) {
            if (product.getCategoria() == 'B') {  // Solo incluir si la categoría es 'C'
                Object[] row = {
                    product.getId(),
                    product.getNombre(),
                    product.getCategoria(),  // Mostrará 'C' en la tabla
                    product.getPrecio(),
                    product.getStock()
                };
                model.addRow(row);
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Error al cargar productos: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMR_ProductosBebida(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boton_FaQBebidas;
    private javax.swing.JToggleButton boton_bookingBebidas;
    private javax.swing.JToggleButton boton_comprarBebidas;
    private javax.swing.JToggleButton boton_eventBebidas;
    private javax.swing.JButton boton_logoBebidas;
    private javax.swing.JToggleButton boton_logoutBebidas;
    private javax.swing.JButton boton_perfilBebidas;
    private javax.swing.JToggleButton boton_productBebidas;
    private javax.swing.JToggleButton boton_salasBebidas;
    private javax.swing.JToggleButton boton_volverBebidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_fondoBebidas;
    private javax.swing.JLabel label_tituloBebidas;
    private javax.swing.JPanel panel_primarioBebidas;
    private javax.swing.JPanel panel_tituloBebidas;
    private javax.swing.JTable tabla_Bebidas;
    // End of variables declaration//GEN-END:variables
}
