/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;
import controller.*;
//import exceptions.*;
import model.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;
//import java.io.IOException;
//import java.net.URISyntaxException;


/**
 *
 * @author LENOVO
 */
public class FMR_ProductosDisponibles extends javax.swing.JFrame {
    private final Account account;
    private final ProductController productController;
    /**
     * Creates new form FMR_ProductosDisponibles
     */
    public FMR_ProductosDisponibles(Account account){
        ProductController tempController;
        try {
            tempController = new ProductController(new FileHandler<>(new Product()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.
                productController = tempController;
        this.account = account;
        Toolkit t=Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("/resources/logo.png")));
        setTitle("LEVELING_UP_LIFE");
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        loadActiveProducts(); // Llamar después de initComponents()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_primarioPdisponibles = new javax.swing.JPanel();
        boton_eventPdisponibles = new javax.swing.JToggleButton();
        boton_productPdisponibles = new javax.swing.JToggleButton();
        boton_salasPdisponibles = new javax.swing.JToggleButton();
        boton_FaQPdisponibles = new javax.swing.JToggleButton();
        boton_bookingPdisponibles = new javax.swing.JToggleButton();
        boton_logoutPdisponibles = new javax.swing.JToggleButton();
        boton_volverPdisponibles = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Pdisponibles = new javax.swing.JTable();
        boton_logoPdisponibles = new javax.swing.JButton();
        panel_tituloPdisponibles = new javax.swing.JPanel();
        boton_perfilPdisponibles = new javax.swing.JButton();
        label_tituloPdisponibles = new javax.swing.JLabel();
        label_fondoPdisponibles = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_primarioPdisponibles.setBackground(new java.awt.Color(252, 240, 198));
        panel_primarioPdisponibles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_primarioPdisponibles.setRequestFocusEnabled(false);
        panel_primarioPdisponibles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_eventPdisponibles.setBackground(new java.awt.Color(51, 153, 0));
        boton_eventPdisponibles.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_eventPdisponibles.setForeground(new java.awt.Color(255, 255, 255));
        boton_eventPdisponibles.setText("Eventos");
        boton_eventPdisponibles.setToolTipText("");
        boton_eventPdisponibles.setAutoscrolls(true);
        boton_eventPdisponibles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_eventPdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eventPdisponiblesActionPerformed(evt);
            }
        });
        panel_primarioPdisponibles.add(boton_eventPdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        boton_productPdisponibles.setBackground(new java.awt.Color(53, 101, 153));
        boton_productPdisponibles.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_productPdisponibles.setForeground(new java.awt.Color(255, 255, 255));
        boton_productPdisponibles.setText("Productos");
        boton_productPdisponibles.setToolTipText("");
        boton_productPdisponibles.setAutoscrolls(true);
        boton_productPdisponibles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_productPdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_productPdisponiblesActionPerformed(evt);
            }
        });
        panel_primarioPdisponibles.add(boton_productPdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 30));

        boton_salasPdisponibles.setBackground(new java.awt.Color(51, 153, 0));
        boton_salasPdisponibles.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_salasPdisponibles.setForeground(new java.awt.Color(255, 255, 255));
        boton_salasPdisponibles.setText("Salas");
        boton_salasPdisponibles.setToolTipText("");
        boton_salasPdisponibles.setAutoscrolls(true);
        boton_salasPdisponibles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_salasPdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salasPdisponiblesActionPerformed(evt);
            }
        });
        panel_primarioPdisponibles.add(boton_salasPdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 30));

        boton_FaQPdisponibles.setBackground(new java.awt.Color(51, 155, 0));
        boton_FaQPdisponibles.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_FaQPdisponibles.setForeground(new java.awt.Color(255, 255, 255));
        boton_FaQPdisponibles.setText("FaQ");
        boton_FaQPdisponibles.setToolTipText("");
        boton_FaQPdisponibles.setAutoscrolls(true);
        boton_FaQPdisponibles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_FaQPdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_FaQPdisponiblesActionPerformed(evt);
            }
        });
        panel_primarioPdisponibles.add(boton_FaQPdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, 30));

        boton_bookingPdisponibles.setBackground(new java.awt.Color(51, 153, 0));
        boton_bookingPdisponibles.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_bookingPdisponibles.setForeground(new java.awt.Color(255, 255, 255));
        boton_bookingPdisponibles.setText("Reservas");
        boton_bookingPdisponibles.setToolTipText("");
        boton_bookingPdisponibles.setAutoscrolls(true);
        boton_bookingPdisponibles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_bookingPdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bookingPdisponiblesActionPerformed(evt);
            }
        });
        panel_primarioPdisponibles.add(boton_bookingPdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 30));

        boton_logoutPdisponibles.setBackground(new java.awt.Color(51, 153, 0));
        boton_logoutPdisponibles.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_logoutPdisponibles.setForeground(new java.awt.Color(255, 255, 255));
        boton_logoutPdisponibles.setText("Cerrar sesion");
        boton_logoutPdisponibles.setToolTipText("");
        boton_logoutPdisponibles.setAutoscrolls(true);
        boton_logoutPdisponibles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_logoutPdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoutPdisponiblesActionPerformed(evt);
            }
        });
        panel_primarioPdisponibles.add(boton_logoutPdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 130, 30));

        boton_volverPdisponibles.setBackground(new java.awt.Color(51, 153, 0));
        boton_volverPdisponibles.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_volverPdisponibles.setForeground(new java.awt.Color(255, 255, 255));
        boton_volverPdisponibles.setText("Volver");
        boton_volverPdisponibles.setToolTipText("");
        boton_volverPdisponibles.setAutoscrolls(true);
        boton_volverPdisponibles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_volverPdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverPdisponiblesActionPerformed(evt);
            }
        });
        panel_primarioPdisponibles.add(boton_volverPdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 150, 30));

        tabla_Pdisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CATEGORIA", "PRECIO", "STOCK"
            }
        ));
        jScrollPane1.setViewportView(tabla_Pdisponibles);

        panel_primarioPdisponibles.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 560, 340));

        boton_logoPdisponibles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        boton_logoPdisponibles.setBorder(null);
        boton_logoPdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoPdisponiblesActionPerformed(evt);
            }
        });
        panel_primarioPdisponibles.add(boton_logoPdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        panel_tituloPdisponibles.setBackground(new java.awt.Color(0, 0, 0));

        boton_perfilPdisponibles.setBackground(new java.awt.Color(0, 0, 0));
        boton_perfilPdisponibles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accBla.png"))); // NOI18N
        boton_perfilPdisponibles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_perfilPdisponibles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_perfilPdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_perfilPdisponiblesActionPerformed(evt);
            }
        });

        label_tituloPdisponibles.setBackground(new java.awt.Color(0, 0, 0));
        label_tituloPdisponibles.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        label_tituloPdisponibles.setForeground(new java.awt.Color(255, 255, 255));
        label_tituloPdisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tituloPdisponibles.setText("Productos Disponibles");
        label_tituloPdisponibles.setToolTipText("");

        javax.swing.GroupLayout panel_tituloPdisponiblesLayout = new javax.swing.GroupLayout(panel_tituloPdisponibles);
        panel_tituloPdisponibles.setLayout(panel_tituloPdisponiblesLayout);
        panel_tituloPdisponiblesLayout.setHorizontalGroup(
            panel_tituloPdisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloPdisponiblesLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(label_tituloPdisponibles)
                .addGap(18, 18, 18)
                .addComponent(boton_perfilPdisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_tituloPdisponiblesLayout.setVerticalGroup(
            panel_tituloPdisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloPdisponiblesLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(boton_perfilPdisponibles)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloPdisponiblesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_tituloPdisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_primarioPdisponibles.add(panel_tituloPdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 100));

        label_fondoPdisponibles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ComidaDisponible.jpg"))); // NOI18N
        panel_primarioPdisponibles.add(label_fondoPdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 640, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_primarioPdisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_primarioPdisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_eventPdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eventPdisponiblesActionPerformed
        FMR_EVENT newFrame = new FMR_EVENT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_eventPdisponiblesActionPerformed

    private void boton_productPdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_productPdisponiblesActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_productPdisponiblesActionPerformed

    private void boton_salasPdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salasPdisponiblesActionPerformed
        FMR_ROOMS newFrame = new FMR_ROOMS(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_salasPdisponiblesActionPerformed

    private void boton_FaQPdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_FaQPdisponiblesActionPerformed
        FMR_FaQ newFrame = new FMR_FaQ(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_FaQPdisponiblesActionPerformed

    private void boton_bookingPdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bookingPdisponiblesActionPerformed
        FMR_BOOKING newFrame = new FMR_BOOKING(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_bookingPdisponiblesActionPerformed

    private void boton_logoutPdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoutPdisponiblesActionPerformed
        FMR_LOGIN newFrame = new FMR_LOGIN();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoutPdisponiblesActionPerformed

    private void boton_volverPdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverPdisponiblesActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_volverPdisponiblesActionPerformed

    private void boton_logoPdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoPdisponiblesActionPerformed
        FMR_CONCEPTO newFrame = new FMR_CONCEPTO(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoPdisponiblesActionPerformed

    private void boton_perfilPdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_perfilPdisponiblesActionPerformed
        FMR_MYACC newFrame = new FMR_MYACC(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_perfilPdisponiblesActionPerformed

    private void loadActiveProducts() {
        try {
        // Obtener productos disponibles del controlador
        List<Product> availableProducts = productController.getAvailableProducts();
        
        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tabla_Pdisponibles.getModel();
        model.setRowCount(0); // Limpiar la tabla
        
        // Llenar la tabla con los productos
        for (Product product : availableProducts) {
            Object[] row = {
                product.getId(),
                product.getNombre(),
                product.getCategoria(),
                product.getPrecio(),
                product.getStock()
            };
            model.addRow(row);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMR_ProductosDisponibles(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boton_FaQPdisponibles;
    private javax.swing.JToggleButton boton_bookingPdisponibles;
    private javax.swing.JToggleButton boton_eventPdisponibles;
    private javax.swing.JButton boton_logoPdisponibles;
    private javax.swing.JToggleButton boton_logoutPdisponibles;
    private javax.swing.JButton boton_perfilPdisponibles;
    private javax.swing.JToggleButton boton_productPdisponibles;
    private javax.swing.JToggleButton boton_salasPdisponibles;
    private javax.swing.JToggleButton boton_volverPdisponibles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_fondoPdisponibles;
    private javax.swing.JLabel label_tituloPdisponibles;
    private javax.swing.JPanel panel_primarioPdisponibles;
    private javax.swing.JPanel panel_tituloPdisponibles;
    private javax.swing.JTable tabla_Pdisponibles;
    // End of variables declaration//GEN-END:variables
}
