/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;
import controller.*;
//import exceptions.*;
import model.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;
//import java.io.IOException;
//import java.net.URISyntaxException;

/**
 *
 * @author LENOVO
 */
public class FMR_ProductosComida extends javax.swing.JFrame {
    private final Account account;
    private final ProductController productController;
    /**
     * Creates new form FMR_ProductosComida
     */
    public FMR_ProductosComida(Account account) {
        ProductController tempController;
        try {
            tempController = new ProductController(new FileHandler<>(new Product()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.
                productController = tempController;
        this.account = account;
        Toolkit t=Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("/resources/logo.png")));
        setTitle("LEVELING_UP_LIFE");
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        loadActiveProducts(); // Llamar después de initComponents()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_primarioComidas = new javax.swing.JPanel();
        boton_comprarComidas = new javax.swing.JToggleButton();
        boton_productComidas = new javax.swing.JToggleButton();
        boton_salasComidas = new javax.swing.JToggleButton();
        boton_FaQComidas = new javax.swing.JToggleButton();
        boton_bookingComidas = new javax.swing.JToggleButton();
        boton_logoutComidas = new javax.swing.JToggleButton();
        boton_volverComidas = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Comidas = new javax.swing.JTable();
        boton_logoComidas = new javax.swing.JButton();
        boton_eventComidas = new javax.swing.JToggleButton();
        panel_tituloPostres = new javax.swing.JPanel();
        boton_perfilComidas = new javax.swing.JButton();
        label_tiuloComidas = new javax.swing.JLabel();
        label_fondoComidas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_primarioComidas.setBackground(new java.awt.Color(252, 240, 198));
        panel_primarioComidas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_primarioComidas.setRequestFocusEnabled(false);
        panel_primarioComidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_comprarComidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_comprarComidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_comprarComidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_comprarComidas.setText("Comprar");
        boton_comprarComidas.setToolTipText("");
        boton_comprarComidas.setAutoscrolls(true);
        boton_comprarComidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_comprarComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_comprarComidasActionPerformed(evt);
            }
        });
        panel_primarioComidas.add(boton_comprarComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 130, 30));

        boton_productComidas.setBackground(new java.awt.Color(53, 101, 153));
        boton_productComidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_productComidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_productComidas.setText("Productos");
        boton_productComidas.setToolTipText("");
        boton_productComidas.setAutoscrolls(true);
        boton_productComidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_productComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_productComidasActionPerformed(evt);
            }
        });
        panel_primarioComidas.add(boton_productComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 30));

        boton_salasComidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_salasComidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_salasComidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_salasComidas.setText("Salas");
        boton_salasComidas.setToolTipText("");
        boton_salasComidas.setAutoscrolls(true);
        boton_salasComidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_salasComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salasComidasActionPerformed(evt);
            }
        });
        panel_primarioComidas.add(boton_salasComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 30));

        boton_FaQComidas.setBackground(new java.awt.Color(51, 155, 0));
        boton_FaQComidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_FaQComidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_FaQComidas.setText("FaQ");
        boton_FaQComidas.setToolTipText("");
        boton_FaQComidas.setAutoscrolls(true);
        boton_FaQComidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_FaQComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_FaQComidasActionPerformed(evt);
            }
        });
        panel_primarioComidas.add(boton_FaQComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, 30));

        boton_bookingComidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_bookingComidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_bookingComidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_bookingComidas.setText("Reservas");
        boton_bookingComidas.setToolTipText("");
        boton_bookingComidas.setAutoscrolls(true);
        boton_bookingComidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_bookingComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bookingComidasActionPerformed(evt);
            }
        });
        panel_primarioComidas.add(boton_bookingComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 30));

        boton_logoutComidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_logoutComidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_logoutComidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_logoutComidas.setText("Cerrar sesion");
        boton_logoutComidas.setToolTipText("");
        boton_logoutComidas.setAutoscrolls(true);
        boton_logoutComidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_logoutComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoutComidasActionPerformed(evt);
            }
        });
        panel_primarioComidas.add(boton_logoutComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 130, 30));

        boton_volverComidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_volverComidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_volverComidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_volverComidas.setText("Volver");
        boton_volverComidas.setToolTipText("");
        boton_volverComidas.setAutoscrolls(true);
        boton_volverComidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_volverComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverComidasActionPerformed(evt);
            }
        });
        panel_primarioComidas.add(boton_volverComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 150, 30));

        tabla_Comidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CATEGORIA", "PRECIO", "STOCK"
            }
        ));
        jScrollPane1.setViewportView(tabla_Comidas);

        panel_primarioComidas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 560, 340));

        boton_logoComidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        boton_logoComidas.setBorder(null);
        boton_logoComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoComidasActionPerformed(evt);
            }
        });
        panel_primarioComidas.add(boton_logoComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        boton_eventComidas.setBackground(new java.awt.Color(51, 153, 0));
        boton_eventComidas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_eventComidas.setForeground(new java.awt.Color(255, 255, 255));
        boton_eventComidas.setText("Eventos");
        boton_eventComidas.setToolTipText("");
        boton_eventComidas.setAutoscrolls(true);
        boton_eventComidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_eventComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eventComidasActionPerformed(evt);
            }
        });
        panel_primarioComidas.add(boton_eventComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        panel_tituloPostres.setBackground(new java.awt.Color(0, 0, 0));

        boton_perfilComidas.setBackground(new java.awt.Color(0, 0, 0));
        boton_perfilComidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accBla.png"))); // NOI18N
        boton_perfilComidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_perfilComidas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_perfilComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_perfilComidasActionPerformed(evt);
            }
        });

        label_tiuloComidas.setBackground(new java.awt.Color(0, 0, 0));
        label_tiuloComidas.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        label_tiuloComidas.setForeground(new java.awt.Color(255, 255, 255));
        label_tiuloComidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_tiuloComidas.setText("COMIDAS");
        label_tiuloComidas.setToolTipText("");

        javax.swing.GroupLayout panel_tituloPostresLayout = new javax.swing.GroupLayout(panel_tituloPostres);
        panel_tituloPostres.setLayout(panel_tituloPostresLayout);
        panel_tituloPostresLayout.setHorizontalGroup(
            panel_tituloPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloPostresLayout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(label_tiuloComidas)
                .addGap(124, 124, 124)
                .addComponent(boton_perfilComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_tituloPostresLayout.setVerticalGroup(
            panel_tituloPostresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tituloPostresLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(boton_perfilComidas)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tituloPostresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_tiuloComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_primarioComidas.add(panel_tituloPostres, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 100));

        label_fondoComidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/categoriaComida.png"))); // NOI18N
        panel_primarioComidas.add(label_fondoComidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 640, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_primarioComidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_primarioComidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_comprarComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_comprarComidasActionPerformed
        int selectedRow = tabla_Comidas.getSelectedRow();
        if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
            "Por favor, seleccione un producto para comprar", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
        }

    // Obtener datos del producto
    String productId = tabla_Comidas.getValueAt(selectedRow, 0).toString();
    String productName = tabla_Comidas.getValueAt(selectedRow, 1).toString();
    double precio = Double.parseDouble(tabla_Comidas.getValueAt(selectedRow, 3).toString());
    int stock = Integer.parseInt(tabla_Comidas.getValueAt(selectedRow, 4).toString());

    // Panel de compra
    JPanel panel = new JPanel(new GridLayout(3, 2));
    JSpinner cantidadSpinner = new JSpinner(new SpinnerNumberModel(1, 1, stock, 1));
    
    panel.add(new JLabel("Producto:"));
    panel.add(new JLabel(productName));
    panel.add(new JLabel("Precio unitario:"));
    panel.add(new JLabel("$" + precio));
    panel.add(new JLabel("Cantidad (Máx: " + stock + "):"));
    panel.add(cantidadSpinner);
    
    int result = JOptionPane.showConfirmDialog(
        this, 
        panel, 
        "Confirmar Compra", 
        JOptionPane.OK_CANCEL_OPTION, 
        JOptionPane.PLAIN_MESSAGE);
    
    if (result == JOptionPane.OK_OPTION) {
        try {
            int cantidad = (int) cantidadSpinner.getValue();
            double total = precio * cantidad;
            
            // Actualizar stock (asumiendo que productController tiene este método)
            productController.updateStock(productId, -cantidad);
            
            JOptionPane.showMessageDialog(this, 
                "Compra realizada!\n" +
                "Producto: " + productName + "\n" +
                "Cantidad: " + cantidad + "\n" +
                "Total: $" + total,
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Actualizar tabla
            loadActiveProducts();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al comprar: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_boton_comprarComidasActionPerformed

    private void boton_productComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_productComidasActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_productComidasActionPerformed

    private void boton_salasComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salasComidasActionPerformed
        FMR_ROOMS newFrame = new FMR_ROOMS(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_salasComidasActionPerformed

    private void boton_FaQComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_FaQComidasActionPerformed
        FMR_FaQ newFrame = new FMR_FaQ(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_FaQComidasActionPerformed

    private void boton_bookingComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bookingComidasActionPerformed
        FMR_BOOKING newFrame = new FMR_BOOKING(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_bookingComidasActionPerformed

    private void boton_logoutComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoutComidasActionPerformed
        FMR_LOGIN newFrame = new FMR_LOGIN();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoutComidasActionPerformed

    private void boton_volverComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverComidasActionPerformed
        FMR_ProductosCategoria newFrame = new FMR_ProductosCategoria(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_volverComidasActionPerformed

    private void boton_logoComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoComidasActionPerformed
        FMR_CONCEPTO newFrame = new FMR_CONCEPTO(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoComidasActionPerformed

    private void boton_perfilComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_perfilComidasActionPerformed
        FMR_MYACC newFrame = new FMR_MYACC(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_perfilComidasActionPerformed

    private void boton_eventComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eventComidasActionPerformed
        FMR_EVENT newFrame = new FMR_EVENT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_eventComidasActionPerformed
    
    private void loadActiveProducts() {
        try {
          // Obtener productos disponibles del controlador
          List<Product> availableProducts = productController.getAvailableProducts();
        
          // Obtener el modelo de la tabla
          DefaultTableModel model = (DefaultTableModel) tabla_Comidas.getModel();
          model.setRowCount(0); // Limpiar la tabla
        
          // Filtrar solo productos de categoría 'C' y llenar la tabla
          for (Product product : availableProducts) {
             if (product.getCategoria() == 'C') {  // Solo incluir si la categoría es 'C'
                Object[] row = {
                    product.getId(),
                    product.getNombre(),
                    product.getCategoria(),  // Mostrará 'C' en la tabla
                    product.getPrecio(),
                    product.getStock()
                };
                model.addRow(row);
             }
          }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, 
              "Error al cargar productos: " + e.getMessage(), 
              "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_ProductosComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMR_ProductosComida(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boton_FaQComidas;
    private javax.swing.JToggleButton boton_bookingComidas;
    private javax.swing.JToggleButton boton_comprarComidas;
    private javax.swing.JToggleButton boton_eventComidas;
    private javax.swing.JButton boton_logoComidas;
    private javax.swing.JToggleButton boton_logoutComidas;
    private javax.swing.JButton boton_perfilComidas;
    private javax.swing.JToggleButton boton_productComidas;
    private javax.swing.JToggleButton boton_salasComidas;
    private javax.swing.JToggleButton boton_volverComidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_fondoComidas;
    private javax.swing.JLabel label_tiuloComidas;
    private javax.swing.JPanel panel_primarioComidas;
    private javax.swing.JPanel panel_tituloPostres;
    private javax.swing.JTable tabla_Comidas;
    // End of variables declaration//GEN-END:variables
}
