package view.gui;

import controller.*;
import exceptions.*;
import model.*;

import javax.swing.*;
import java.awt.*;


/**
 *
 * @author KNKOW-RIC
 */
public class FMR_REGISTRO extends javax.swing.JFrame {
    private final AccountController accountController;
    /**
     * Creates new form FMR_REGISTRO
     */
    public FMR_REGISTRO() {
        AccountController tempController;
        try {
            tempController = new AccountController(new FileHandler<>(new Account()));
        } catch (AccountException e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.accountController = tempController;
        Toolkit t=Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("/resources/logo.png")));
        setTitle("LEVELING_UP_LIFE");
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        setupPlaceholders();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        campo_name = new javax.swing.JTextField();
        name_separator = new javax.swing.JSeparator();
        campo_last = new javax.swing.JTextField();
        last_separator = new javax.swing.JSeparator();
        campo_phone = new javax.swing.JTextField();
        phone_separator = new javax.swing.JSeparator();
        campo_email = new javax.swing.JTextField();
        email_separator = new javax.swing.JSeparator();
        campo_user = new javax.swing.JTextField();
        user_separator = new javax.swing.JSeparator();
        campo_pass = new javax.swing.JPasswordField();
        pass_separator = new javax.swing.JSeparator();
        button_volver = new javax.swing.JToggleButton();
        button_registro = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEVELING");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(252, 240, 198));
        setFocusCycleRoot(false);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(400, 580));
        setPreferredSize(new java.awt.Dimension(400, 580));
        setSize(new java.awt.Dimension(400, 580));

        BG.setBackground(new java.awt.Color(252, 240, 198));
        BG.setMinimumSize(new java.awt.Dimension(400, 580));
        BG.setPreferredSize(new java.awt.Dimension(400, 580));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        BG.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 150, 150));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titulo.setText("Crear cuenta");
        BG.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 210, -1));

        campo_name.setBackground(new java.awt.Color(252, 240, 198));
        campo_name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campo_name.setForeground(new java.awt.Color(102, 102, 102));
        campo_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_name.setText(" Nombre");
        campo_name.setBorder(null);
        campo_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nameActionPerformed(evt);
            }
        });
        BG.add(campo_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 30));

        name_separator.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(name_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 20));

        campo_last.setBackground(new java.awt.Color(252, 240, 198));
        campo_last.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campo_last.setForeground(new java.awt.Color(102, 102, 102));
        campo_last.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_last.setText("Apellido");
        campo_last.setBorder(null);
        campo_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_lastActionPerformed(evt);
            }
        });
        BG.add(campo_last, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 160, 30));

        last_separator.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(last_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 170, 10));

        campo_phone.setBackground(new java.awt.Color(252, 240, 198));
        campo_phone.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campo_phone.setForeground(new java.awt.Color(102, 102, 102));
        campo_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_phone.setText("Telefono");
        campo_phone.setBorder(null);
        campo_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_phoneActionPerformed(evt);
            }
        });
        BG.add(campo_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 260, 30));

        phone_separator.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(phone_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 260, 10));

        campo_email.setBackground(new java.awt.Color(252, 240, 198));
        campo_email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campo_email.setForeground(new java.awt.Color(102, 102, 102));
        campo_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_email.setText("Direccion de correo electronico");
        campo_email.setBorder(null);
        campo_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_emailActionPerformed(evt);
            }
        });
        BG.add(campo_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 260, 30));

        email_separator.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(email_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 260, 10));

        campo_user.setBackground(new java.awt.Color(252, 240, 198));
        campo_user.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campo_user.setForeground(new java.awt.Color(102, 102, 102));
        campo_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_user.setText("Usuario");
        campo_user.setBorder(null);
        campo_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_userActionPerformed(evt);
            }
        });
        BG.add(campo_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 260, 30));

        user_separator.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(user_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 260, -1));

        campo_pass.setBackground(new java.awt.Color(252, 240, 198));
        campo_pass.setForeground(new java.awt.Color(102, 102, 102));
        campo_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_pass.setText("Ingrese su Contraseña");
        campo_pass.setBorder(null);
        BG.add(campo_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 260, 30));

        pass_separator.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(pass_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 260, 10));

        button_volver.setBackground(new java.awt.Color(51, 153, 0));
        button_volver.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        button_volver.setForeground(new java.awt.Color(255, 255, 255));
        button_volver.setText("Volver");
        button_volver.setToolTipText("");
        button_volver.setAutoscrolls(true);
        button_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_volverActionPerformed(evt);
            }
        });
        BG.add(button_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 130, 30));

        button_registro.setBackground(new java.awt.Color(51, 153, 0));
        button_registro.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        button_registro.setForeground(new java.awt.Color(255, 255, 255));
        button_registro.setText("Registrarse");
        button_registro.setToolTipText("");
        button_registro.setAutoscrolls(true);
        button_registro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registroActionPerformed(evt);
            }
        });
        BG.add(button_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_nameActionPerformed(java.awt.event.ActionEvent evt) {}

    private void campo_phoneActionPerformed(java.awt.event.ActionEvent evt) {}

    private void campo_emailActionPerformed(java.awt.event.ActionEvent evt) {}

    private void campo_lastActionPerformed(java.awt.event.ActionEvent evt) {}

    private void campo_userActionPerformed(java.awt.event.ActionEvent evt) {}

    private void button_volverActionPerformed(java.awt.event.ActionEvent evt) {
        FMR_LOGIN newFrame = new FMR_LOGIN(); 
        newFrame.setVisible(true);
        this.dispose();
    }

    private void button_registroActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Account newAccount = new Account(
                campo_name.getText().trim(),
                campo_last.getText().trim(),
                campo_phone.getText().trim(),
                campo_email.getText().trim(),
                campo_user.getText().trim(),
                new String(campo_pass.getPassword()).trim()
            );
            
            accountController.registerAccount(newAccount);
            
            // Mostrar mensaje de éxito usando JOptionPane directamente
            JOptionPane.showMessageDialog(
                this,
                "Registro Exitoso",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            // Redirigir al login
            FMR_LOGIN loginFrame = new FMR_LOGIN();
            loginFrame.setVisible(true);
            this.dispose();
            
        } catch (AccountException e) {
            JOptionPane.showMessageDialog(
                this,
                "Error al registrar: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_button_registroActionPerformed

    private void setupPlaceholders() {
        // Nombre
        campo_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (campo_name.getText().trim().equals("Nombre")) {
                    campo_name.setText("");
                    campo_name.setForeground(new Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (campo_name.getText().isEmpty()) {
                    campo_name.setText("Nombre");
                    campo_name.setForeground(new Color(102, 102, 102));
                }
            }
        });

        // Apellido
        campo_last.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (campo_last.getText().trim().equals("Apellido")) {
                    campo_last.setText("");
                    campo_last.setForeground(new Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (campo_last.getText().isEmpty()) {
                    campo_last.setText("Apellido");
                    campo_last.setForeground(new Color(102, 102, 102));
                }
            }
        });

        // Teléfono
        campo_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (campo_phone.getText().trim().equals("Telefono")) {
                    campo_phone.setText("");
                    campo_phone.setForeground(new Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (campo_phone.getText().isEmpty()) {
                    campo_phone.setText("Telefono");
                    campo_phone.setForeground(new Color(102, 102, 102));
                }
            }
        });

        // Email
        campo_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (campo_email.getText().trim().equals("Direccion de correo electronico")) {
                    campo_email.setText("");
                    campo_email.setForeground(new Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (campo_email.getText().isEmpty()) {
                    campo_email.setText("Direccion de correo electronico");
                    campo_email.setForeground(new Color(102, 102, 102));
                }
            }
        });

        // Usuario
        campo_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (campo_user.getText().trim().equals("Usuario")) {
                    campo_user.setText("");
                    campo_user.setForeground(new Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (campo_user.getText().isEmpty()) {
                    campo_user.setText("Usuario");
                    campo_user.setForeground(new Color(102, 102, 102));
                }
            }
        });

        // Contraseña
        campo_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (new String(campo_pass.getPassword()).equals("Ingrese su Contraseña")) {
                    campo_pass.setText("");
                    campo_pass.setForeground(new Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (new String(campo_pass.getPassword()).isEmpty()) {
                    campo_pass.setText("Ingrese su Contraseña");
                    campo_pass.setForeground(new Color(102, 102, 102));
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FMR_REGISTRO().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JToggleButton button_registro;
    private javax.swing.JToggleButton button_volver;
    private javax.swing.JTextField campo_email;
    private javax.swing.JTextField campo_last;
    private javax.swing.JTextField campo_name;
    private javax.swing.JPasswordField campo_pass;
    private javax.swing.JTextField campo_phone;
    private javax.swing.JTextField campo_user;
    private javax.swing.JSeparator email_separator;
    private javax.swing.JSeparator last_separator;
    private javax.swing.JLabel logo;
    private javax.swing.JSeparator name_separator;
    private javax.swing.JSeparator pass_separator;
    private javax.swing.JSeparator phone_separator;
    private javax.swing.JLabel titulo;
    private javax.swing.JSeparator user_separator;
    // End of variables declaration//GEN-END:variables
}
