package view.gui;

import controller.*;
import exceptions.*;
import model.*;

import javax.swing.*;
import java.awt.*;

/**
 * @author ARUBIS
 */
public class FMR_RomsTipo extends javax.swing.JFrame {
    private final Account account;
    private final RoomController roomController;
    
    /**
     * Creates new form FMR_Hti
     */
    public FMR_RomsTipo(Account account) {
        RoomController tempController;
        try {
            tempController = new RoomController(new FileHandler<>(new Room()));
        } catch (RoomException e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.roomController = tempController;
        this.account = account;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        TITULO = new javax.swing.JPanel();
        boton_myCuenta = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        boton_verIndividual = new javax.swing.JToggleButton();
        boton_verPrivadas = new javax.swing.JToggleButton();
        boton_verMixta = new javax.swing.JToggleButton();
        boton_verDormitorio = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boton_voverRoomTipo = new javax.swing.JToggleButton();
        boton_events = new javax.swing.JToggleButton();
        boton_product = new javax.swing.JToggleButton();
        boton_salas = new javax.swing.JToggleButton();
        boton_FaQ = new javax.swing.JToggleButton();
        boton_booking = new javax.swing.JToggleButton();
        boton_logout = new javax.swing.JToggleButton();
        boton_concepto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(875, 555));
        setPreferredSize(new java.awt.Dimension(875, 555));
        setSize(new java.awt.Dimension(875, 555));

        BG.setBackground(new java.awt.Color(252, 240, 198));
        BG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BG.setMinimumSize(new java.awt.Dimension(860, 520));
        BG.setPreferredSize(new java.awt.Dimension(860, 520));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setBackground(new java.awt.Color(0, 0, 0));

        boton_myCuenta.setBackground(new java.awt.Color(0, 0, 0));
        boton_myCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accBla.png"))); // NOI18N
        boton_myCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_myCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_myCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_myCuentaActionPerformed(evt);
            }
        });

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("SALAS");
        titulo.setToolTipText("");

        javax.swing.GroupLayout TITULOLayout = new javax.swing.GroupLayout(TITULO);
        TITULO.setLayout(TITULOLayout);
        TITULOLayout.setHorizontalGroup(
            TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TITULOLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(boton_myCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TITULOLayout.setVerticalGroup(
            TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TITULOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_myCuenta)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BG.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 100));

        boton_verIndividual.setBackground(new java.awt.Color(51, 153, 0));
        boton_verIndividual.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_verIndividual.setForeground(new java.awt.Color(255, 255, 255));
        boton_verIndividual.setText("Ver");
        boton_verIndividual.setToolTipText("");
        boton_verIndividual.setAutoscrolls(true);
        boton_verIndividual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_verIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_verIndividualActionPerformed(evt);
            }
        });
        BG.add(boton_verIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 105, 30));

        boton_verPrivadas.setBackground(new java.awt.Color(51, 153, 0));
        boton_verPrivadas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_verPrivadas.setForeground(new java.awt.Color(255, 255, 255));
        boton_verPrivadas.setText("Ver");
        boton_verPrivadas.setToolTipText("");
        boton_verPrivadas.setAutoscrolls(true);
        boton_verPrivadas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_verPrivadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_verPrivadasActionPerformed(evt);
            }
        });
        BG.add(boton_verPrivadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 105, 30));

        boton_verMixta.setBackground(new java.awt.Color(51, 153, 0));
        boton_verMixta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_verMixta.setForeground(new java.awt.Color(255, 255, 255));
        boton_verMixta.setText("Ver");
        boton_verMixta.setToolTipText("");
        boton_verMixta.setAutoscrolls(true);
        boton_verMixta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_verMixta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_verMixtaActionPerformed(evt);
            }
        });
        BG.add(boton_verMixta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 105, 30));

        boton_verDormitorio.setBackground(new java.awt.Color(51, 153, 0));
        boton_verDormitorio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_verDormitorio.setForeground(new java.awt.Color(255, 255, 255));
        boton_verDormitorio.setText("Ver");
        boton_verDormitorio.setToolTipText("");
        boton_verDormitorio.setAutoscrolls(true);
        boton_verDormitorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_verDormitorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_verDormitorioActionPerformed(evt);
            }
        });
        BG.add(boton_verDormitorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 105, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tipoRoom.png"))); // NOI18N
        BG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 370));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        boton_voverRoomTipo.setBackground(new java.awt.Color(51, 153, 0));
        boton_voverRoomTipo.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        boton_voverRoomTipo.setForeground(new java.awt.Color(255, 255, 255));
        boton_voverRoomTipo.setText("Volver");
        boton_voverRoomTipo.setToolTipText("");
        boton_voverRoomTipo.setAutoscrolls(true);
        boton_voverRoomTipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_voverRoomTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_voverRoomTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(504, Short.MAX_VALUE)
                .addComponent(boton_voverRoomTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boton_voverRoomTipo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        BG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 640, 50));

        boton_events.setBackground(new java.awt.Color(51, 153, 0));
        boton_events.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_events.setForeground(new java.awt.Color(255, 255, 255));
        boton_events.setText("Eventos");
        boton_events.setToolTipText("");
        boton_events.setAutoscrolls(true);
        boton_events.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_events.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eventsActionPerformed(evt);
            }
        });
        BG.add(boton_events, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 130, 30));

        boton_product.setBackground(new java.awt.Color(51, 153, 0));
        boton_product.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_product.setForeground(new java.awt.Color(255, 255, 255));
        boton_product.setText("Productos");
        boton_product.setToolTipText("");
        boton_product.setAutoscrolls(true);
        boton_product.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_productActionPerformed(evt);
            }
        });
        BG.add(boton_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 130, 30));

        boton_salas.setBackground(new java.awt.Color(43, 101, 153));
        boton_salas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_salas.setForeground(new java.awt.Color(255, 255, 255));
        boton_salas.setText("Salas");
        boton_salas.setToolTipText("");
        boton_salas.setAutoscrolls(true);
        boton_salas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_salas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salasActionPerformed(evt);
            }
        });
        BG.add(boton_salas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 130, 30));

        boton_FaQ.setBackground(new java.awt.Color(51, 153, 0));
        boton_FaQ.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_FaQ.setForeground(new java.awt.Color(255, 255, 255));
        boton_FaQ.setText("FaQ");
        boton_FaQ.setToolTipText("");
        boton_FaQ.setAutoscrolls(true);
        boton_FaQ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_FaQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_FaQActionPerformed(evt);
            }
        });
        BG.add(boton_FaQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 130, 30));

        boton_booking.setBackground(new java.awt.Color(51, 153, 0));
        boton_booking.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_booking.setForeground(new java.awt.Color(255, 255, 255));
        boton_booking.setText("Reservas");
        boton_booking.setToolTipText("");
        boton_booking.setAutoscrolls(true);
        boton_booking.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bookingActionPerformed(evt);
            }
        });
        BG.add(boton_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 130, 30));

        boton_logout.setBackground(new java.awt.Color(51, 153, 0));
        boton_logout.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_logout.setForeground(new java.awt.Color(255, 255, 255));
        boton_logout.setText("Cerrar sesion");
        boton_logout.setToolTipText("");
        boton_logout.setAutoscrolls(true);
        boton_logout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logoutActionPerformed(evt);
            }
        });
        BG.add(boton_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 130, 30));

        boton_concepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        boton_concepto.setBorder(null);
        boton_concepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_conceptoActionPerformed(evt);
            }
        });
        BG.add(boton_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_voverRoomTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_voverRoomTipoActionPerformed
        FMR_ROOMS newFrame = new FMR_ROOMS(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_voverRoomTipoActionPerformed

    private void boton_verDormitorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_verDormitorioActionPerformed
        FMR_RoomsDormitorio newFrame = new FMR_RoomsDormitorio(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_verDormitorioActionPerformed

    private void boton_verMixtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_verMixtaActionPerformed
        FMR_RoomsMixtas newFrame = new FMR_RoomsMixtas(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_verMixtaActionPerformed

    private void boton_verPrivadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_verPrivadasActionPerformed
        FMR_RoomsPrivadas newFrame = new FMR_RoomsPrivadas(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_verPrivadasActionPerformed

    private void boton_verIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_verIndividualActionPerformed
        FMR_RoomsIndividual newFrame = new FMR_RoomsIndividual(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_verIndividualActionPerformed

    private void boton_myCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_myCuentaActionPerformed
        FMR_MYACC newFrame = new FMR_MYACC(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_myCuentaActionPerformed

    private void boton_eventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eventsActionPerformed
        FMR_EVENT newFrame = new FMR_EVENT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_eventsActionPerformed

    private void boton_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_productActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_productActionPerformed

    private void boton_salasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salasActionPerformed
        FMR_ROOMS newFrame = new FMR_ROOMS(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_salasActionPerformed

    private void boton_FaQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_FaQActionPerformed
        FMR_FaQ newFrame = new FMR_FaQ(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_FaQActionPerformed

    private void boton_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bookingActionPerformed
        FMR_BOOKING newFrame = new FMR_BOOKING(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_bookingActionPerformed

    private void boton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logoutActionPerformed
        FMR_LOGIN newFrame = new FMR_LOGIN();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logoutActionPerformed

    private void boton_conceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_conceptoActionPerformed
        FMR_CONCEPTO newFrame = new FMR_CONCEPTO(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_conceptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMR_RomsTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMR_RomsTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMR_RomsTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_RomsTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FMR_RomsTipo(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel TITULO;
    private javax.swing.JToggleButton boton_FaQ;
    private javax.swing.JToggleButton boton_booking;
    private javax.swing.JButton boton_concepto;
    private javax.swing.JToggleButton boton_events;
    private javax.swing.JToggleButton boton_logout;
    private javax.swing.JButton boton_myCuenta;
    private javax.swing.JToggleButton boton_product;
    private javax.swing.JToggleButton boton_salas;
    private javax.swing.JToggleButton boton_verDormitorio;
    private javax.swing.JToggleButton boton_verIndividual;
    private javax.swing.JToggleButton boton_verMixta;
    private javax.swing.JToggleButton boton_verPrivadas;
    private javax.swing.JToggleButton boton_voverRoomTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
