package view.gui;

import controller.*;
import exceptions.*;
import model.*;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.net.URISyntaxException;

/**
 * @author DAVID FT KNOWLES
 */
public class FMR_BOOKING extends javax.swing.JFrame {
    private final Account account;
    private final BookingController bookingController;
    
    /**
     * Creates new form FMR_FaQ
     */
    public FMR_BOOKING(Account account) {
        BookingController tempController;
        try {
            tempController = new BookingController(new FileHandler<>(new Booking()), new RoomController(new FileHandler<>(new Room())));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.bookingController = tempController;
        this.account = account;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        boton_events = new javax.swing.JToggleButton();
        boton_product = new javax.swing.JToggleButton();
        boton_salas = new javax.swing.JToggleButton();
        boton_FaQ = new javax.swing.JToggleButton();
        boton_booking = new javax.swing.JToggleButton();
        boton_REvento = new javax.swing.JToggleButton();
        Crear = new javax.swing.JToggleButton();
        MisReservas = new javax.swing.JToggleButton();
        Historial = new javax.swing.JToggleButton();
        boton_concepto = new javax.swing.JButton();
        TITULO = new javax.swing.JPanel();
        boton_myCuenta = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boton_logout1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(875, 555));

        BG.setBackground(new java.awt.Color(252, 240, 198));
        BG.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BG.setMinimumSize(new java.awt.Dimension(860, 520));
        BG.setPreferredSize(new java.awt.Dimension(860, 520));
        BG.setRequestFocusEnabled(false);
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_events.setBackground(new java.awt.Color(51, 153, 0));
        boton_events.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_events.setForeground(new java.awt.Color(255, 255, 255));
        boton_events.setText("Eventos");
        boton_events.setToolTipText("");
        boton_events.setAutoscrolls(true);
        boton_events.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_events.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eventsActionPerformed(evt);
            }
        });
        BG.add(boton_events, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 30));

        boton_product.setBackground(new java.awt.Color(51, 153, 0));
        boton_product.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_product.setForeground(new java.awt.Color(255, 255, 255));
        boton_product.setText("Productos");
        boton_product.setToolTipText("");
        boton_product.setAutoscrolls(true);
        boton_product.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_productActionPerformed(evt);
            }
        });
        BG.add(boton_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 130, 30));

        boton_salas.setBackground(new java.awt.Color(51, 153, 0));
        boton_salas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_salas.setForeground(new java.awt.Color(255, 255, 255));
        boton_salas.setText("Salas");
        boton_salas.setToolTipText("");
        boton_salas.setAutoscrolls(true);
        boton_salas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_salas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salasActionPerformed(evt);
            }
        });
        BG.add(boton_salas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 130, 30));

        boton_FaQ.setBackground(new java.awt.Color(51, 153, 0));
        boton_FaQ.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_FaQ.setForeground(new java.awt.Color(255, 255, 255));
        boton_FaQ.setText("FaQ");
        boton_FaQ.setToolTipText("");
        boton_FaQ.setAutoscrolls(true);
        boton_FaQ.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_FaQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_FaQActionPerformed(evt);
            }
        });
        BG.add(boton_FaQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 130, 30));

        boton_booking.setBackground(new java.awt.Color(43, 101, 153));
        boton_booking.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_booking.setForeground(new java.awt.Color(255, 255, 255));
        boton_booking.setText("Reservas");
        boton_booking.setToolTipText("");
        boton_booking.setAutoscrolls(true);
        boton_booking.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bookingActionPerformed(evt);
            }
        });
        BG.add(boton_booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 130, 30));

        boton_REvento.setBackground(new java.awt.Color(51, 153, 0));
        boton_REvento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_REvento.setForeground(new java.awt.Color(255, 255, 255));
        boton_REvento.setText("R.Evento");
        boton_REvento.setToolTipText("");
        boton_REvento.setAutoscrolls(true);
        boton_REvento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_REvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_REventoActionPerformed(evt);
            }
        });
        BG.add(boton_REvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 130, 30));

        Crear.setBackground(new java.awt.Color(51, 153, 0));
        Crear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Crear.setForeground(new java.awt.Color(255, 255, 255));
        Crear.setText("R.Habitacion");
        Crear.setToolTipText("");
        Crear.setAutoscrolls(true);
        Crear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });
        BG.add(Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 130, 30));

        MisReservas.setBackground(new java.awt.Color(51, 153, 0));
        MisReservas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MisReservas.setForeground(new java.awt.Color(255, 255, 255));
        MisReservas.setText("Mis Reservas");
        MisReservas.setToolTipText("");
        MisReservas.setAutoscrolls(true);
        MisReservas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MisReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MisReservasActionPerformed(evt);
            }
        });
        BG.add(MisReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 130, 30));

        Historial.setBackground(new java.awt.Color(51, 153, 0));
        Historial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Historial.setForeground(new java.awt.Color(255, 255, 255));
        Historial.setText("Historial");
        Historial.setToolTipText("");
        Historial.setAutoscrolls(true);
        Historial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialActionPerformed(evt);
            }
        });
        BG.add(Historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 130, 30));

        boton_concepto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        boton_concepto.setBorder(null);
        boton_concepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_conceptoActionPerformed(evt);
            }
        });
        BG.add(boton_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        TITULO.setBackground(new java.awt.Color(0, 0, 0));

        boton_myCuenta.setBackground(new java.awt.Color(0, 0, 0));
        boton_myCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/accBla.png"))); // NOI18N
        boton_myCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_myCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton_myCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_myCuentaActionPerformed(evt);
            }
        });

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("RESERVAS");
        titulo.setToolTipText("");

        javax.swing.GroupLayout TITULOLayout = new javax.swing.GroupLayout(TITULO);
        TITULO.setLayout(TITULOLayout);
        TITULOLayout.setHorizontalGroup(
            TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TITULOLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_myCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TITULOLayout.setVerticalGroup(
            TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TITULOLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TITULOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_myCuenta)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BG.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 640, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cuartoverde.jpg"))); // NOI18N
        BG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 640, 420));

        boton_logout1.setBackground(new java.awt.Color(51, 153, 0));
        boton_logout1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_logout1.setForeground(new java.awt.Color(255, 255, 255));
        boton_logout1.setText("Cerrar sesion");
        boton_logout1.setToolTipText("");
        boton_logout1.setAutoscrolls(true);
        boton_logout1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_logout1ActionPerformed(evt);
            }
        });
        BG.add(boton_logout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_productActionPerformed
        FMR_PRODUCT newFrame = new FMR_PRODUCT(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_productActionPerformed

    private void boton_salasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salasActionPerformed
        FMR_ROOMS newFrame = new FMR_ROOMS(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_salasActionPerformed

    private void boton_FaQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_FaQActionPerformed
        FMR_FaQ newFrame = new FMR_FaQ(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_FaQActionPerformed

    private void boton_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bookingActionPerformed
        FMR_BOOKING newFrame = new FMR_BOOKING(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_bookingActionPerformed

    private void boton_REventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_REventoActionPerformed
        FMR_EventosReservas newFrame = new FMR_EventosReservas(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_REventoActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
     FMR_B_Crear newFrame = new FMR_B_Crear(account); 
        newFrame.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_CrearActionPerformed

    private void boton_eventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eventsActionPerformed
        FMR_EVENT newFrame = new FMR_EVENT(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_eventsActionPerformed

    private void boton_conceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_conceptoActionPerformed
        FMR_CONCEPTO newFrame = new FMR_CONCEPTO(account); 
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_conceptoActionPerformed

    private void boton_myCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_myCuentaActionPerformed
        FMR_MYACC newFrame = new FMR_MYACC(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_myCuentaActionPerformed

    private void HistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialActionPerformed
        FMR_B_HIST newFrame = new FMR_B_HIST(account);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HistorialActionPerformed

    private void MisReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MisReservasActionPerformed
     FMR_B_MisR newFrame = new FMR_B_MisR(account);
        newFrame.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_MisReservasActionPerformed

    private void boton_logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_logout1ActionPerformed
     FMR_LOGIN newFrame = new FMR_LOGIN();
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_logout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_BOOKING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FMR_BOOKING(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JToggleButton Crear;
    private javax.swing.JToggleButton Historial;
    private javax.swing.JToggleButton MisReservas;
    private javax.swing.JPanel TITULO;
    private javax.swing.JToggleButton boton_FaQ;
    private javax.swing.JToggleButton boton_REvento;
    private javax.swing.JToggleButton boton_booking;
    private javax.swing.JButton boton_concepto;
    private javax.swing.JToggleButton boton_events;
    private javax.swing.JToggleButton boton_logout1;
    private javax.swing.JButton boton_myCuenta;
    private javax.swing.JToggleButton boton_product;
    private javax.swing.JToggleButton boton_salas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}