package view.gui;

import controller.*;
import exceptions.*;
import model.*;
import view.console.*;

import javax.swing.*;
import java.awt.*;

/**
 * @author KNKOW-RIC
 */
public class FMR_LOGIN extends javax.swing.JFrame {
    private final AccountController accountController;
    /**
     * Creates new form FMR_RLR
     */
    public FMR_LOGIN() {
        AccountController tempController;
        try {
            tempController = new AccountController(new FileHandler<>(new Account()));
        } catch (AccountException e) {
            JOptionPane.showMessageDialog(null, "Error al inicializar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            tempController = null;
            System.exit(1);
        }
        this.accountController = tempController;
        initComponents();
        setLocationRelativeTo(null);
        setupPlaceholders();
    }

    private void setupPlaceholders() {
        // Add focus listeners for placeholder behavior
        campo_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (campo_user.getText().equals("Ingrese su nombre de usuario")) {
                    campo_user.setText("");
                    campo_user.setForeground(new java.awt.Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (campo_user.getText().isEmpty()) {
                    campo_user.setText("Ingrese su nombre de usuario");
                    campo_user.setForeground(new java.awt.Color(102, 102, 102));
                }
            }
        });

        campo_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (String.valueOf(campo_pass.getPassword()).equals("Ingrese su contraseña")) {
                    campo_pass.setText("");
                    campo_pass.setForeground(new java.awt.Color(0, 0, 0));
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (String.valueOf(campo_pass.getPassword()).isEmpty()) {
                    campo_pass.setText("Ingrese su contraseña");
                    campo_pass.setForeground(new java.awt.Color(102, 102, 102));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        registrp = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        campo_user = new javax.swing.JTextField();
        user_separator = new javax.swing.JSeparator();
        pass_separator = new javax.swing.JSeparator();
        campo_pass = new javax.swing.JPasswordField();
        boton_login = new javax.swing.JToggleButton();
        boton_createAcc = new javax.swing.JButton();
        boton_restroreAcc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEVELING");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(252, 240, 198));
        setFocusCycleRoot(false);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(400, 580));
        setPreferredSize(new java.awt.Dimension(400, 580));
        setSize(new java.awt.Dimension(400, 580));

        BG.setBackground(new java.awt.Color(252, 240, 198));
        BG.setMinimumSize(new java.awt.Dimension(420, 500));
        BG.setPreferredSize(new java.awt.Dimension(420, 500));
        BG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N
        BG.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, 150));

        registrp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        registrp.setText("¿Aun no tienes cuenta?");
        BG.add(registrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        titulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titulo.setText("Acceder a mi cuenta");
        BG.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        campo_user.setBackground(new java.awt.Color(252, 240, 198));
        campo_user.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        campo_user.setForeground(new java.awt.Color(102, 102, 102));
        campo_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_user.setText("Ingrese su nombre de usuario");
        campo_user.setToolTipText("");
        campo_user.setBorder(null);
        campo_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_userActionPerformed(evt);
            }
        });
        BG.add(campo_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 260, 30));

        user_separator.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(user_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 260, 10));

        pass_separator.setForeground(new java.awt.Color(0, 0, 0));
        BG.add(pass_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 260, 10));

        campo_pass.setBackground(new java.awt.Color(252, 240, 198));
        campo_pass.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        campo_pass.setForeground(new java.awt.Color(102, 102, 102));
        campo_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campo_pass.setText("Ingrese su contraseña");
        campo_pass.setToolTipText("");
        campo_pass.setActionCommand("<Not Set>");
        campo_pass.setBorder(null);
        campo_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_passActionPerformed(evt);
            }
        });
        BG.add(campo_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 260, 30));

        boton_login.setBackground(new java.awt.Color(51, 153, 0));
        boton_login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        boton_login.setForeground(new java.awt.Color(255, 255, 255));
        boton_login.setText("Inicio de sesion ");
        boton_login.setToolTipText("");
        boton_login.setAutoscrolls(true);
        boton_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_loginActionPerformed(evt);
            }
        });
        BG.add(boton_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 140, -1));

        boton_createAcc.setBackground(new java.awt.Color(252, 240, 198));
        boton_createAcc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        boton_createAcc.setForeground(new java.awt.Color(51, 102, 255));
        boton_createAcc.setText(" Crear una cuenta");
        boton_createAcc.setBorder(null);
        boton_createAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_createAccActionPerformed(evt);
            }
        });
        BG.add(boton_createAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        boton_restroreAcc.setBackground(new java.awt.Color(252, 240, 198));
        boton_restroreAcc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        boton_restroreAcc.setText("¿Has olvidado tu contraseña?");
        boton_restroreAcc.setBorder(null);
        boton_restroreAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_restroreAccActionPerformed(evt);
            }
        });
        BG.add(boton_restroreAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campo_userActionPerformed(java.awt.event.ActionEvent evt) {}

    private void boton_loginActionPerformed(java.awt.event.ActionEvent evt) {
        String username = campo_user.getText().trim();
        String password = new String(campo_pass.getPassword()).trim();

        // Validate empty fields
        if (username.isEmpty() || username.equals("Ingrese su nombre de usuario") ||
            password.isEmpty() || password.equals("Ingrese su contraseña")) {
            JOptionPane.showMessageDialog(this,
                "Por favor complete todos los campos",
                "Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Account loggedAccount = accountController.login(username, password);
            
            // Check if password needs to be changed
            if (password.equals("L3V3L1NG_up_L1F3")) {
                JOptionPane.showMessageDialog(this,
                    "Por favor, cambie su contraseña",
                    "Cambio de Contraseña Requerido",
                    JOptionPane.INFORMATION_MESSAGE);
                    
                String newPassword;
                do {
                    newPassword = JOptionPane.showInputDialog(this,
                        "Ingrese su nueva contraseña:",
                        "Cambio de Contraseña",
                        JOptionPane.PLAIN_MESSAGE);
                        
                    if (newPassword == null || newPassword.trim().isEmpty()) {
                        JOptionPane.showMessageDialog(this,
                            "La contraseña no puede estar vacía",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    }
                } while (newPassword == null || newPassword.trim().isEmpty());
                
                accountController.updatePassword(username, "L3V3L1NG_up_L1F3", newPassword);
            }

            // Custom success dialog with color
            JPanel panel = new JPanel();
            JLabel label = new JLabel("¡Bienvenido " + loggedAccount.getNombre() + "!");
            panel.add(label);
            
            JOptionPane.showOptionDialog(
                this,
                panel,
                "Login Exitoso",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                new Object[]{"OK"},
                null
            );
            
            // Open appropriate menu based on user type
            if (loggedAccount.isAdmin()) {
                this.dispose(); // Close the current window first
                MainMenuController mainMenu = new MainMenuController(loggedAccount);
                mainMenu.start(); // This will start the console interface
            } else {
                FMR_CONCEPTO userMenu = new FMR_CONCEPTO(loggedAccount);
                userMenu.setVisible(true);
            }
            
            this.dispose();
            
        } catch (AccountException e) {
            JOptionPane.showMessageDialog(this, 
                "Error al iniciar sesión: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void campo_passActionPerformed(java.awt.event.ActionEvent evt) {}

    private void boton_createAccActionPerformed(java.awt.event.ActionEvent evt) {                                                
        FMR_REGISTRO newFrame = new FMR_REGISTRO(); 
        newFrame.setVisible(true);
        this.dispose();
        
    }

    private void boton_restroreAccActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        FMR_RECUPERACION newFrame = new FMR_RECUPERACION(); 
        newFrame.setVisible(true);
        this.dispose();
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMR_LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FMR_LOGIN().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JButton boton_createAcc;
    private javax.swing.JToggleButton boton_login;
    private javax.swing.JButton boton_restroreAcc;
    private javax.swing.JPasswordField campo_pass;
    private javax.swing.JTextField campo_user;
    private javax.swing.JLabel logo;
    private javax.swing.JSeparator pass_separator;
    private javax.swing.JLabel registrp;
    private javax.swing.JLabel titulo;
    private javax.swing.JSeparator user_separator;
    // End of variables declaration//GEN-END:variables
}
